{
  "hash": "45eb17f59c8524d241d9957be854cab8",
  "result": {
    "markdown": "---\ntitle: \"Hands-on Exercise 3\"\nauthor: Zhu Yiting\nexecute: \n  warning: false\n  message: false\n  freeze: auto\nformat: html\neditor: visual\n---\n\n\n# Geographical Segmentation with Spatially Constrained Clustering Techniques\n\n## 1. Overview\n\nThis exercise aims to delineate homogeneous regions by using geographically referenced multivariate data. There are two main analyses, namely:\n\n1.  hierarchical cluster analysis; and\n2.  spatially constrained cluster analysis.\n\n### 1.1. Learning Objectives\n\n1.  Convert GIS polygon data into R's simple feature data.frame by using appropriate functions of **sf** package.\n2.  Convert simple feature data.frame into R's SpatialPolygonDataFrame object by using appropriate functions of **sf** package.\n3.  Perform cluster analysis using *hclust()* of **Base R**.\n4.  Perform spatially constrained cluster analysis using *skater()* of **Base R**.\n5.  Visualise analysis output using **ggplot2** and **tmap** packages.\n\n## 2. Getting Started\n\n### 2.1. The Analytical Question\n\nIn geobusiness and spatial policy, it is common practice to delineate the market or planning areas into homogeneous regions by using multivariate data. In this hands-on exercise, we are interested to delineate [Shan State](https://en.wikipedia.org/wiki/Shan_State), [Myanmar](https://en.wikipedia.org/wiki/Myanmar), into homogeneous regions by using multiple Information and Community Technology (ICT) measures, namely: Radio, Telephone, Land line phone, Mobile phone, Computer and Internet at home.\n\n### 2.2. The Data\n\nTwo data sets will be used in this study:\n\n1.  Myanmar Township Boundary Data (i.e. `myanmar_township_boundaries`). This is a GIS data in ESRI shapefile format. It consists of township boundary information of Myanmar. The spatial data are captured in polygon features.\n2.  `Shan-ICT.csv`. This is an extract of the [2014 Myanmar Population and Housing Census Myanmar](https://myanmar.unfpa.org/en/publications/2014-population-and-housing-census-myanmar-data-sheet), at the township level.\n\nBoth data sets were downloaded from [Myanmar Information Management Unit (MIMU)](http://themimu.info/).\n\n## 3. Installing and Loading R Packages\n\nWe will prepare our R environment by installing and loading the necessary R packages, using [*p_load()*](https://www.rdocumentation.org/packages/pacman/versions/0.5.1/topics/p_load) function of [**pacman**](https://www.rdocumentation.org/packages/pacman/versions/0.5.1) package.\n\nThe R packages needed for this exercise are as follows:\n\n1.  Spatial data handling - [**sf**](https://r-spatial.github.io/sf/), [**rgdal**](http://cran.nexr.com/web/packages/rgdal/index.html) and [**spdep**](https://www.rdocumentation.org/packages/spdep/versions/1.2-7)\n2.  Attribute data handling - [**tidyverse**](https://www.tidyverse.org/), specifically [**readr**](https://readr.tidyverse.org/), [**ggplot2**](https://ggplot2.tidyverse.org/) and [**dplyr**](https://dplyr.tidyverse.org/)\n3.  Choropleth mapping - [**tmap**](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html)\n4.  Multivariate data visualisation and analysis - [**coorplot**](https://www.rdocumentation.org/packages/corrplot/versions/0.92), [**ggpubr**](https://www.rdocumentation.org/packages/ggpubr/versions/0.5.0), [**factoextra**](https://www.rdocumentation.org/packages/factoextra/versions/1.0.7) and [**heatmaply**](https://www.rdocumentation.org/packages/heatmaply/versions/1.4.0)\n5.  Cluster analysis - [**cluster**](https://cran.r-project.org/web/packages/cluster/index.html), [**NbClust**](https://www.rdocumentation.org/packages/NbClust/versions/3.0.1/topics/NbClust), [**ClustGeo**](https://hal.archives-ouvertes.fr/hal-01664018/file/pub00056373.pdf)and [**psych**](https://www.rdocumentation.org/packages/psych/versions/2.2.9)\n\nThe code chunk below installs and loads the required R packages into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(rgdal, spdep, tmap, sf, \n               ggpubr, cluster, factoextra, NbClust, \n               heatmaply, corrplot, psych, tidyverse)\n```\n:::\n\n\n## 4. Data Import and Preperation\n\n### 4.1. Importing Geospatial Data into R Environment\n\nIn this section, we import Myanmar Township Boundary GIS data and its associated attribute table into the R environment.\n\nThe Myanmar Township Boundary GIS data is in ESRI shapefile format. We can import it into the R environment using [*st_read()*](https://r-spatial.github.io/sf/reference/st_read.html) of **sf**. We also use the piping function *%\\>%* from **dplyr** and perform *filter()* to extract only the data for the Shan state. This is done in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf <- st_read(dsn = \"data/geospatial\",\n                   layer = \"myanmar_township_boundaries\") %>% \n  filter(ST %in% c(\"Shan (East)\", \"Shan (North)\", \"Shan (South)\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `myanmar_township_boundaries' from data source \n  `C:\\zhuyiting1\\ISSS624\\Hands-on_Ex3\\data\\geospatial' using driver `ESRI Shapefile'\nSimple feature collection with 330 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.17275 ymin: 9.671252 xmax: 101.1699 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n:::\n:::\n\n\nThe imported Myanmar township boundary object is assigned to `shan_sf`. It is saved in **simple feature data.frame** format. We see that the full shapefile before filtering for Shan state has 330 features and 14 fields, which should include **multipolygon** geometry as its last field based on the geometry type displayed. Looking at the Environment pane, we see that `shan_sf` is filtered down to 55 observations. The bounding box shows the range of x and y, which are between 9 and 102 and suggests that the data is in [decimal degrees format](https://www.maptools.com/tutorials/lat_lon/formats). The coordinate reference system (CRS) used is geographic, in [**wgs84**](https://gisgeography.com/wgs84-world-geodetic-system/).\n\nWe can view the content of `shan_sf` simple features data.frame by calling it directly, using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 55 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 96.15107 ymin: 19.29932 xmax: 101.1699 ymax: 24.15907\nGeodetic CRS:  WGS 84\nFirst 10 features:\n   OBJECTID           ST ST_PCODE       DT   DT_PCODE        TS  TS_PCODE\n1       163 Shan (North)   MMR015  Mongmit MMR015D008   Mongmit MMR015017\n2       203 Shan (South)   MMR014 Taunggyi MMR014D001   Pindaya MMR014006\n3       240 Shan (South)   MMR014 Taunggyi MMR014D001   Ywangan MMR014007\n4       106 Shan (South)   MMR014 Taunggyi MMR014D001  Pinlaung MMR014009\n5        72 Shan (North)   MMR015  Mongmit MMR015D008    Mabein MMR015018\n6        40 Shan (South)   MMR014 Taunggyi MMR014D001     Kalaw MMR014005\n7       194 Shan (South)   MMR014 Taunggyi MMR014D001     Pekon MMR014010\n8       159 Shan (South)   MMR014 Taunggyi MMR014D001  Lawksawk MMR014008\n9        61 Shan (North)   MMR015  Kyaukme MMR015D003 Nawnghkio MMR015013\n10      124 Shan (North)   MMR015  Kyaukme MMR015D003   Kyaukme MMR015012\n                 ST_2            LABEL2 SELF_ADMIN ST_RG T_NAME_WIN T_NAME_M3\n1  Shan State (North)    Mongmit\\n61072       <NA> State   rdk;rdwf      မိုးမိတ်\n2  Shan State (South)    Pindaya\\n77769       Danu State     yif;w,     ပင်းတယ\n3  Shan State (South)    Ywangan\\n76933       Danu State      &GmiH       ရွာငံ\n4  Shan State (South)  Pinlaung\\n162537       Pa-O State  yifavmif;   ပင်လောင်း\n5  Shan State (North)     Mabein\\n35718       <NA> State     rbdrf;      မဘိမ်း\n6  Shan State (South)     Kalaw\\n163138       <NA> State       uavm      ကလော\n7  Shan State (South)      Pekon\\n94226       <NA> State     z,fcHk       ဖယ်ခုံ\n8  Shan State (South)          Lawksawk       <NA> State   &yfapmuf    ရပ်စောက်\n9  Shan State (North) Nawnghkio\\n128357       <NA> State  aemifcsdK    နောင်ချို\n10 Shan State (North)   Kyaukme\\n172874       <NA> State   ausmufrJ    ကျောက်မဲ\n       AREA                       geometry\n1  2703.611 MULTIPOLYGON (((96.96001 23...\n2   629.025 MULTIPOLYGON (((96.7731 21....\n3  2984.377 MULTIPOLYGON (((96.78483 21...\n4  3396.963 MULTIPOLYGON (((96.49518 20...\n5  5034.413 MULTIPOLYGON (((96.66306 24...\n6  1456.624 MULTIPOLYGON (((96.49518 20...\n7  2073.513 MULTIPOLYGON (((97.14738 19...\n8  5145.659 MULTIPOLYGON (((96.94981 22...\n9  3271.537 MULTIPOLYGON (((96.75648 22...\n10 3920.869 MULTIPOLYGON (((96.95498 22...\n```\n:::\n:::\n\n\nAs the sf.data.frame conforms to Hardy Wickham's [tidy framework](https://edzer.github.io/rstudio_conf/#18), we can use [*glimpse()*](https://dplyr.tidyverse.org/reference/glimpse.html) of **dplyr** to check the data types of its fields.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(shan_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 55\nColumns: 15\n$ OBJECTID   <dbl> 163, 203, 240, 106, 72, 40, 194, 159, 61, 124, 71, 155, 101…\n$ ST         <chr> \"Shan (North)\", \"Shan (South)\", \"Shan (South)\", \"Shan (Sout…\n$ ST_PCODE   <chr> \"MMR015\", \"MMR014\", \"MMR014\", \"MMR014\", \"MMR015\", \"MMR014\",…\n$ DT         <chr> \"Mongmit\", \"Taunggyi\", \"Taunggyi\", \"Taunggyi\", \"Mongmit\", \"…\n$ DT_PCODE   <chr> \"MMR015D008\", \"MMR014D001\", \"MMR014D001\", \"MMR014D001\", \"MM…\n$ TS         <chr> \"Mongmit\", \"Pindaya\", \"Ywangan\", \"Pinlaung\", \"Mabein\", \"Kal…\n$ TS_PCODE   <chr> \"MMR015017\", \"MMR014006\", \"MMR014007\", \"MMR014009\", \"MMR015…\n$ ST_2       <chr> \"Shan State (North)\", \"Shan State (South)\", \"Shan State (So…\n$ LABEL2     <chr> \"Mongmit\\n61072\", \"Pindaya\\n77769\", \"Ywangan\\n76933\", \"Pinl…\n$ SELF_ADMIN <chr> NA, \"Danu\", \"Danu\", \"Pa-O\", NA, NA, NA, NA, NA, NA, NA, NA,…\n$ ST_RG      <chr> \"State\", \"State\", \"State\", \"State\", \"State\", \"State\", \"Stat…\n$ T_NAME_WIN <chr> \"rdk;rdwf\", \"yif;w,\", \"&GmiH\", \"yifavmif;\", \"rbdrf;\", \"uavm…\n$ T_NAME_M3  <chr> \"မိုးမိတ်\", \"ပင်းတယ\", \"ရွာငံ\", \"ပင်လောင်း\", \"မဘိမ်း\", \"ကလော\", \"ဖယ်ခုံ\", \"…\n$ AREA       <dbl> 2703.611, 629.025, 2984.377, 3396.963, 5034.413, 1456.624, …\n$ geometry   <MULTIPOLYGON [°]> MULTIPOLYGON (((96.96001 23..., MULTIPOLYGON (…\n```\n:::\n:::\n\n\n### 4.2. Importing Aspatial Data into R Environment\n\nThe csv file is imported using [*read_csv()*](https://readr.tidyverse.org/reference/read_delim.html) of **readr** using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nict <- read_csv(\"data/aspatial/Shan-ICT.csv\")\n```\n:::\n\n\nThe imported attribute data set is saved in R's tibble data.frame format and named `ict`. We see that it also has 55 observations, and 11 columns which include the number of households for each ICT variable from the 2014 Myanmar Population and Housing Census Myanmar.\n\nThe code chunk below uses *summary()* of **Base R** to show the summary statistics for each of the 11 variables in the `ict` data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n District Pcode     District Name      Township Pcode     Township Name     \n Length:55          Length:55          Length:55          Length:55         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n Total households     Radio         Television    Land line phone \n Min.   : 3318    Min.   :  115   Min.   :  728   Min.   :  20.0  \n 1st Qu.: 8711    1st Qu.: 1260   1st Qu.: 3744   1st Qu.: 266.5  \n Median :13685    Median : 2497   Median : 6117   Median : 695.0  \n Mean   :18369    Mean   : 4487   Mean   :10183   Mean   : 929.9  \n 3rd Qu.:23471    3rd Qu.: 6192   3rd Qu.:13906   3rd Qu.:1082.5  \n Max.   :82604    Max.   :30176   Max.   :62388   Max.   :6736.0  \n  Mobile phone      Computer      Internet at home\n Min.   :  150   Min.   :  20.0   Min.   :   8.0  \n 1st Qu.: 2037   1st Qu.: 121.0   1st Qu.:  88.0  \n Median : 3559   Median : 244.0   Median : 316.0  \n Mean   : 6470   Mean   : 575.5   Mean   : 760.2  \n 3rd Qu.: 7177   3rd Qu.: 507.0   3rd Qu.: 630.5  \n Max.   :48461   Max.   :6705.0   Max.   :9746.0  \n```\n:::\n:::\n\n\nThe highest number among the maximum values is 62,388 households for television, which is consistent with our knowledge of it being a common source of entertainment and communication method in this era.\n\n### 4.3. Deriving New Variables Using **dplyr** Package\n\nThe unit of measurement of the values are the number of households. Using these values directly will be biased by the underlying total number of households. In general, the townships with relative higher total number of households will also have higher absolute number of households owning radio, television, etc.\n\nIn order to overcome this problem, we will derive the penetration rate of each ICT variable, using the [*mutate()*](https://dplyr.tidyverse.org/reference/mutate.html) function of **dplyr** to create new columns as shown in the code chunk below. We also use [*rename()*](https://dplyr.tidyverse.org/reference/rename.html) of **dplyr** to make the variable names more easily understood and when using them in the *mutate()* functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nict_derived <- ict %>%\n  mutate(`RADIO_PR` = `Radio`/`Total households`*1000) %>%\n  mutate(`TV_PR` = `Television`/`Total households`*1000) %>%\n  mutate(`LLPHONE_PR` = `Land line phone`/`Total households`*1000) %>%\n  mutate(`MPHONE_PR` = `Mobile phone`/`Total households`*1000) %>%\n  mutate(`COMPUTER_PR` = `Computer`/`Total households`*1000) %>%\n  mutate(`INTERNET_PR` = `Internet at home`/`Total households`*1000) %>%\n  rename(`DT_PCODE`=`District Pcode`,`DT`=`District Name`,\n         `TS_PCODE`=`Township Pcode`, `TS`=`Township Name`,\n         `TT_HOUSEHOLDS`=`Total households`,\n         `RADIO`=`Radio`, `TV`=`Television`, \n         `LLPHONE`=`Land line phone`, `MPHONE`=`Mobile phone`,\n         `COMPUTER`=`Computer`, `INTERNET`=`Internet at home`) \n```\n:::\n\n\nWe can see that the new variables are appended to the`ict` data.frame in `ict_derived`, using the *summary()* function of **Base R**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ict_derived)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   DT_PCODE              DT              TS_PCODE              TS           \n Length:55          Length:55          Length:55          Length:55         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n TT_HOUSEHOLDS       RADIO             TV           LLPHONE      \n Min.   : 3318   Min.   :  115   Min.   :  728   Min.   :  20.0  \n 1st Qu.: 8711   1st Qu.: 1260   1st Qu.: 3744   1st Qu.: 266.5  \n Median :13685   Median : 2497   Median : 6117   Median : 695.0  \n Mean   :18369   Mean   : 4487   Mean   :10183   Mean   : 929.9  \n 3rd Qu.:23471   3rd Qu.: 6192   3rd Qu.:13906   3rd Qu.:1082.5  \n Max.   :82604   Max.   :30176   Max.   :62388   Max.   :6736.0  \n     MPHONE         COMPUTER         INTERNET         RADIO_PR     \n Min.   :  150   Min.   :  20.0   Min.   :   8.0   Min.   : 21.05  \n 1st Qu.: 2037   1st Qu.: 121.0   1st Qu.:  88.0   1st Qu.:138.95  \n Median : 3559   Median : 244.0   Median : 316.0   Median :210.95  \n Mean   : 6470   Mean   : 575.5   Mean   : 760.2   Mean   :215.68  \n 3rd Qu.: 7177   3rd Qu.: 507.0   3rd Qu.: 630.5   3rd Qu.:268.07  \n Max.   :48461   Max.   :6705.0   Max.   :9746.0   Max.   :484.52  \n     TV_PR         LLPHONE_PR       MPHONE_PR       COMPUTER_PR    \n Min.   :116.0   Min.   :  2.78   Min.   : 36.42   Min.   : 3.278  \n 1st Qu.:450.2   1st Qu.: 22.84   1st Qu.:190.14   1st Qu.:11.832  \n Median :517.2   Median : 37.59   Median :305.27   Median :18.970  \n Mean   :509.5   Mean   : 51.09   Mean   :314.05   Mean   :24.393  \n 3rd Qu.:606.4   3rd Qu.: 69.72   3rd Qu.:428.43   3rd Qu.:29.897  \n Max.   :842.5   Max.   :181.49   Max.   :735.43   Max.   :92.402  \n  INTERNET_PR     \n Min.   :  1.041  \n 1st Qu.:  8.617  \n Median : 22.829  \n Mean   : 30.644  \n 3rd Qu.: 41.281  \n Max.   :117.985  \n```\n:::\n:::\n\n\nThe derived proportions range between 1.041 for the Internet and 842.4 for television.\n\n### 4.4. Joining Geospatial and Aspatial Data\n\nWe combine both sets of data into a single data.frame using [*left_join()*](https://dplyr.tidyverse.org/reference/mutate-joins.html) of **dplyr**, which appends the second data.frame to the first based on the observations in the first. The `shan_sf` simple feature data.frame will be used as the base data object, and the `ict_derived` data.frame will be used as the join table.\n\nAs there are 4 variables which are common across both data sets, namely `DT`, `DT_PCODE`, `TS`, and `TS_PCODE`, we will specify the criteria for joining, in this case by `TS_PCODE`. We do so using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf <- left_join(shan_sf, \n                     ict_derived, \n                     by=c(\"TS_PCODE\"=\"TS_PCODE\"))\n```\n:::\n\n\n## 5. Exploratory Data Analysis (EDA)\n\n### 5.1. EDA Using Statistical Graphics\n\nWe plot the distribution of variables (i.e. number of households with radio) using appropriate Exploratory Data Analysis (EDA) using the combination [*ggplot()*](https://ggplot2.tidyverse.org/reference/ggplot.html) (to initialise a ggplot object) with [*geom_histogram()*](https://ggplot2.tidyverse.org/reference/geom_histogram.html) (to plot a histogram) of **ggplot2** as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = shan_sf, \n       aes(x = `RADIO`)) +\n  geom_histogram(bins = 20, \n                 color = \"black\", \n                 fill = \"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nSeeing the distribution being right-skewed and having counts that are far out to the right and disjoint from the rest of the frequency bars, we also use [*geom_boxplot()*](https://ggplot2.tidyverse.org/reference/geom_boxplot.html) of **ggplot2** to plot a boxplot, which is useful for detecting outliers which are displayed as individual points outside of the box-and-whiskers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = shan_sf,\n       aes(x = `RADIO`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe see 3 individual dots displayed outside of the box-and-whiskers, signifying 3 outliers beyond 12,500 households.\n\nNext, we also plot the distribution of the newly derived variable (i.e. Radio penetration rate (PR)) by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = shan_sf, \n       aes(x = `RADIO_PR`)) +\n  geom_histogram(bins = 20, \n                 color = \"black\", \n                 fill = \"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nWe see that the Radio PR appears more normal with less outliers, but still slightly right-skewed.\n\nWe similarly plot the boxplot for Radio PR using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = shan_sf, \n       aes(x = `RADIO_PR`)) +\n  geom_boxplot(color = \"black\", \n               fill = \"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nWe can repeat the process for all 6 modes of ICT in the data, and combine them into a single figure using [*ggarrange()*](https://rpkgs.datanovia.com/ggpubr/reference/ggarrange.html) of **ggpubr** to group and arrange the plots (in a similar way to [*tmap_arrange()*](https://r-tmap.github.io/tmap/reference/tmap_arrange.html) of **tmap**, except for ggplots instead of tmaps).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradio <- ggplot(data=shan_sf, \n             aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ntv <- ggplot(data=shan_sf, \n             aes(x=`TV_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nllphone <- ggplot(data=shan_sf, \n             aes(x=`LLPHONE_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nmphone <- ggplot(data=shan_sf, \n             aes(x=`MPHONE_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ncomputer <- ggplot(data=shan_sf, \n             aes(x=`COMPUTER_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ninternet <- ggplot(data=shan_sf, \n             aes(x=`INTERNET_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nggarrange(radio, tv, llphone, mphone, computer, internet, \n          ncol = 3, \n          nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nFrom the histograms, we see that all ICT PRs are right-skewed with potential outliers, except TV PR which is left-skewed. We confirm this using boxplots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradio <- ggplot(data=shan_sf, \n             aes(x=`RADIO_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\ntv <- ggplot(data=shan_sf, \n             aes(x=`TV_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\nllphone <- ggplot(data=shan_sf, \n             aes(x=`LLPHONE_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\nmphone <- ggplot(data=shan_sf, \n             aes(x=`MPHONE_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\ncomputer <- ggplot(data=shan_sf, \n             aes(x=`COMPUTER_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\ninternet <- ggplot(data=shan_sf, \n             aes(x=`INTERNET_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n\nggarrange(radio, tv, llphone, mphone, computer, internet, \n          ncol = 3, \n          nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nIt turns out that TV PR has outliers on both the left and right of the box-and-whiskers. In addition, for mobile phone PR, there is no outlier.\n\n### 5.2. EDA Using Choropleth Map\n\nTo have a quick look at the distribution of Radio PR of Shan State at township level, we will use a choropleth map.\n\nThe code chunk below plots a choropleth map using [*qtm()*](https://www.rdocumentation.org/packages/tmap/versions/3.3-3/topics/qtm) of **tmap**. This is a quick and easy way to get a quick view of the spatial distribution, coloured by 5 equal intervals, by simply specifying (i) the simple feature data.frame and (ii) the variable by which to colour the map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqtm(shan_sf, \"RADIO_PR\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nWe see darker regions of Radio PR in the extreme Northwest, along the West side and in the Southeast side of Shan State.\n\nIn order to reveal that the distribution shown in the choropleth map above is biased to the underlying total number of households at the townships, we will create two choropleth maps, one for the total number of households (i.e. TT_HOUSEHOLD.map) and the other for the total number of households with Radio (RADIO.map), using\n\n-   [*tm_shape()*](https://www.rdocumentation.org/packages/tmap/versions/3.3-3/topics/tm_shape)- to plot the geometries of the sf data.frame,\n\n-   [*tm_fill()*](https://www.rdocumentation.org/packages/tmap/versions/3.3-3/topics/tm_fill) - to specify the variable by which the polygons are coloured, number of intervals, types of intervals (e.g. equal, quantile), displayed title of the legend, and display of histogram of the values of variable plotted,\n\n-   [*tm_borders()*](https://www.rdocumentation.org/packages/tmap/versions/0.7/topics/tm_borders) - to customise the border properties such as transparency,\n\n-   [*tm_layout()*](https://www.rdocumentation.org/packages/tmap/versions/3.3-3/topics/tm_layout) - to customise the plot layout such as the title of plot, size of legend, position of title and legend, and\n\n-   [*tmap_arrange()*](https://www.rdocumentation.org/packages/tmap/versions/0.7/topics/tm_borders) - to plot multiple tmaps\n\nof **tmap** in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTT_HOUSEHOLDS.map <- tm_shape(shan_sf) + \n  tm_fill(col = \"TT_HOUSEHOLDS\",\n          n = 5,\n          style = \"jenks\", \n          title = \"Total households\",\n          legend.hist = TRUE) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"Total number of households\",\n            main.title.size = 1,\n            main.title.position = \"center\",\n            legend.outside = TRUE)\n\nRADIO.map <- tm_shape(shan_sf) + \n  tm_fill(col = \"RADIO\",\n          n = 5,\n          style = \"jenks\",\n          title = \"Number Radio \",\n          legend.hist = TRUE) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"Number of households with Radio\",\n            main.title.size = 1,\n            main.title.position = \"center\",\n            legend.outside = TRUE)\n\ntmap_arrange(TT_HOUSEHOLDS.map, RADIO.map,\n             asp=NA, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nWe use [`style = \"jenks\"`](https://en.wikipedia.org/wiki/Jenks_natural_breaks_optimization) which identifies groups of similar values in the data, and maximises the difference between categories.\n\nWe note that the choropleth maps above show that townships with relatively larger number of households are also showing relatively higher number of Radio ownership, as seen in the darker coloured regions.\n\nWe plot the choropleth maps showing the distribution of the total number of households and Radio PR using the code chunk below. Here we use *tm_polygons()*, *tm_facets()* and *tm_legend()* instead from **tmap** to plot the two maps side-by-side easily.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(shan_sf) +\n    tm_polygons(c(\"TT_HOUSEHOLDS\", \"RADIO_PR\"),\n                style=\"jenks\") +\n    tm_facets(sync = TRUE, ncol = 2) +\n  tm_legend(legend.position = c(\"right\", \"bottom\"))+\n  tm_layout(outer.margins=0, asp=0)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nHere, we see that the Radio PR is no longer directly correlated with the total number of households. In particular, we see that there are dark red regions in the extreme Northwest, in the Southwest and Southeast regions in the Radio PR plot on the right, but are yellow or light orange in the total households plot on the left. This removes the bias from the underlying household distribution!\n\n## 6. Correlation Analysis\n\nBefore we perform cluster analysis, it is important for us to ensure that the cluster variables are not highly correlated. This is because if highly correlated variables are used for cluster analysis, specific aspects covered by these variables will be over-represented in the clustering solution. In this regard, absolute correlation (r) above 0.85 are problematic and should be avoided by removing either one of the pair of highly correlated variables.\n\nWe use [*corrplot.mixed()*](https://www.rdocumentation.org/packages/corrplot/versions/0.92/topics/corrplot.mixed) of [**corrplot**](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) to visualise and analyse the correlation of the input variables, using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_vars.cor = cor(ict_derived[,12:17])\ncorrplot.mixed(cluster_vars.cor,\n         lower = \"ellipse\", \n               upper = \"number\",\n               tl.pos = \"lt\",\n               diag = \"l\",\n               tl.col = \"black\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThe correlation plot above shows that `COMPUTER_PR` and `INTERNET_PR` are highly correlated (r = 0.87 \\> 0.85). This suggest that only one of them should be used in the cluster analysis instead of both. In this exercise, we will use `COMPUTER_PR` instead of `INTERNET_PR` as the former provides direct output and interaction with users, similar to other ICT variables in this data set.\n\n## 7. Hierarchical Cluster Analysis\n\n### 7.1. Extracting Clustering Variables\n\nThe code chunk below will be used to extract the clustering variables from the *shan_sf* simple feature object into data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_vars <- shan_sf %>%\n  st_set_geometry(NULL) %>%\n  select(\"TS.x\", \"RADIO_PR\", \"TV_PR\", \"LLPHONE_PR\", \"MPHONE_PR\", \"COMPUTER_PR\")\nhead(cluster_vars,10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        TS.x RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\n1    Mongmit 286.1852 554.1313   35.30618  260.6944    12.15939\n2    Pindaya 417.4647 505.1300   19.83584  162.3917    12.88190\n3    Ywangan 484.5215 260.5734   11.93591  120.2856     4.41465\n4   Pinlaung 231.6499 541.7189   28.54454  249.4903    13.76255\n5     Mabein 449.4903 708.6423   72.75255  392.6089    16.45042\n6      Kalaw 280.7624 611.6204   42.06478  408.7951    29.63160\n7      Pekon 318.6118 535.8494   39.83270  214.8476    18.97032\n8   Lawksawk 387.1017 630.0035   31.51366  320.5686    21.76677\n9  Nawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\n10   Kyaukme 210.9548 601.1773   39.58267  372.4930    30.94709\n```\n:::\n:::\n\n\nNext, we need to change the rows by township name instead of row number by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrow.names(cluster_vars) <- cluster_vars$\"TS.x\"\nhead(cluster_vars,10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               TS.x RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\nMongmit     Mongmit 286.1852 554.1313   35.30618  260.6944    12.15939\nPindaya     Pindaya 417.4647 505.1300   19.83584  162.3917    12.88190\nYwangan     Ywangan 484.5215 260.5734   11.93591  120.2856     4.41465\nPinlaung   Pinlaung 231.6499 541.7189   28.54454  249.4903    13.76255\nMabein       Mabein 449.4903 708.6423   72.75255  392.6089    16.45042\nKalaw         Kalaw 280.7624 611.6204   42.06478  408.7951    29.63160\nPekon         Pekon 318.6118 535.8494   39.83270  214.8476    18.97032\nLawksawk   Lawksawk 387.1017 630.0035   31.51366  320.5686    21.76677\nNawnghkio Nawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\nKyaukme     Kyaukme 210.9548 601.1773   39.58267  372.4930    30.94709\n```\n:::\n:::\n\n\nNow, we will delete the TS.x field which is a duplicate of the row names now, by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict <- select(cluster_vars, c(2:6))\nhead(shan_ict, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\nMongmit   286.1852 554.1313   35.30618  260.6944    12.15939\nPindaya   417.4647 505.1300   19.83584  162.3917    12.88190\nYwangan   484.5215 260.5734   11.93591  120.2856     4.41465\nPinlaung  231.6499 541.7189   28.54454  249.4903    13.76255\nMabein    449.4903 708.6423   72.75255  392.6089    16.45042\nKalaw     280.7624 611.6204   42.06478  408.7951    29.63160\nPekon     318.6118 535.8494   39.83270  214.8476    18.97032\nLawksawk  387.1017 630.0035   31.51366  320.5686    21.76677\nNawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\nKyaukme   210.9548 601.1773   39.58267  372.4930    30.94709\n```\n:::\n:::\n\n\n### 7.2. Data Standardisation\n\nIn general, multiple variables will be used in cluster analysis. It is not unusual their values range are different. In order to avoid the cluster analysis result is baised to clustering variables with large values, it is useful to standardise the input variables before performing cluster analysis. Some common variable standardisation techniques are:\n\n1.  Z-score - transforms normal variants to standard score form;\n2.  Min-Max - transforms data to a value between 0 and 1; and\n3.  Decimal Scaling - normalises by moving the decimal points of the maximum value of the variable to \\<1.\n\n### 7.3. Z-score Standardisation\n\nZ-score standardisation can be performed easily by using [*scale()*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/scale) of **Base R**. The code chunk below will be used to stadardisation the clustering variables by using Z-score method, and then displays the summary statistics of the clustering variables using [*describe()*](https://www.rdocumentation.org/packages/Hmisc/versions/4.7-2/topics/describe) of **psych** to display standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict.z <- scale(shan_ict)\npsych::describe(shan_ict.z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            vars  n mean sd median trimmed  mad   min  max range  skew kurtosis\nRADIO_PR       1 55    0  1  -0.04   -0.06 0.94 -1.85 2.55  4.40  0.48    -0.27\nTV_PR          2 55    0  1   0.05    0.04 0.78 -2.47 2.09  4.56 -0.38    -0.23\nLLPHONE_PR     3 55    0  1  -0.33   -0.15 0.68 -1.19 3.20  4.39  1.37     1.49\nMPHONE_PR      4 55    0  1  -0.05   -0.06 1.01 -1.58 2.40  3.98  0.48    -0.34\nCOMPUTER_PR    5 55    0  1  -0.26   -0.18 0.64 -1.03 3.31  4.34  1.80     2.96\n              se\nRADIO_PR    0.13\nTV_PR       0.13\nLLPHONE_PR  0.13\nMPHONE_PR   0.13\nCOMPUTER_PR 0.13\n```\n:::\n:::\n\n\nThe mean and standard deviation of the Z-score standardised clustering variables are 0 and 1 respectively by virtue of Z-score standardisation.\n\nNote that Z-score standardisation method should only be use if all variables come from normal distribution.\n\n### 7.4. Min-Max Standardisation\n\nIn the code chunk below, *normalize()* of [**heatmaply**](https://cran.r-project.org/web/packages/heatmaply/) is used to stadardise the clustering variables by using Min-Max method. The *summary()* of **Base R** is then used to display the summary statistics of the standardised clustering variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict.std <- normalize(shan_ict)\nsummary(shan_ict.std)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    RADIO_PR          TV_PR          LLPHONE_PR       MPHONE_PR     \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.2544   1st Qu.:0.4600   1st Qu.:0.1123   1st Qu.:0.2199  \n Median :0.4097   Median :0.5523   Median :0.1948   Median :0.3846  \n Mean   :0.4199   Mean   :0.5416   Mean   :0.2703   Mean   :0.3972  \n 3rd Qu.:0.5330   3rd Qu.:0.6750   3rd Qu.:0.3746   3rd Qu.:0.5608  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n  COMPUTER_PR     \n Min.   :0.00000  \n 1st Qu.:0.09598  \n Median :0.17607  \n Mean   :0.23692  \n 3rd Qu.:0.29868  \n Max.   :1.00000  \n```\n:::\n:::\n\n\nWe see that the value range of the Min-Max standarised clustering variables is now within 0 and 1 (inclusive).\n\n### 7.5. Visualising the Standardised Clustering Variables\n\nBeside reviewing the summary statistics of the standardised clustering variables, it is also a good practice to visualise their distribution graphical.\n\nThe code chunk below plot the scaled `Radio_PR` field.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- ggplot(data=ict_derived, \n             aes(x= `RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Non-standardised\")\n\nshan_ict_s_df <- as.data.frame(shan_ict.std)\ns <- ggplot(data=shan_ict_s_df, \n       aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Min-Max Standardisation\")\n\nshan_ict_z_df <- as.data.frame(shan_ict.z)\nz <- ggplot(data=shan_ict_z_df, \n       aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Z-score Standardisation\")\n\nggarrange(r, s, z,\n          ncol = 3,\n          nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nWe see that before standardisation, the distribution appears to be right-skewed, hence Z-score standardisation may not be the best option if we wish to use standardised data. Nevertheless, the general shape of the distribution is similar across both standardisation methods.\n\nNotice that the overall distribution of the clustering variables will change after the data standardisation. Hence, it is advisible **NOT** to perform data standardisation if the values range of the clustering variables are not very large. In this case, as we earlier saw that the PRs of all ICTs analysed are in the scale of 0-100, we will proceed with clustering analysis using the non-standardised PRs.\n\nOn the other hand, it is advisable that heavily skewed data are first transformed to a more symmetric distribution. The general variable transformation techniques are:\n\n1.  Log transformation - taking the natural log of the clustering variables;\n2.  Square root - taking the square root of the variables; and\n3.  Windorising - replacing all values greater than x percentile with the xth percentile and values less than (100-x)th percentile with the values of the (100-x)th percentile. This reduces the effects of outliers on statistical analyses, particularly hierarchical clustering which is sensitive to noise and outliers.\n\nIn this exercise, we see that the clustering variables are neither heavily skewed (only a slight right-skew for most ICT PRs) nor have many extreme outliers (up to 3). Hence, we will not perform variable transformation.\n\n### 7.6. Computing Proximity Matrix\n\nIn R, many packages provide functions to calculate distance matrix. We will compute the proximity matrix by using [*dist()*](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/dist.html) of **R stats**.\n\n*dist()* supports six distance proximity calculations, they are: `euclidean`,`maximum`,`manhattan`,`canberra`,`binary` and `minkowski`. The default is `euclidean` proximity matrix.\n\nThe code chunk below is used to compute the proximity matrix using `euclidean` method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproxmat <- dist(shan_ict, method = 'euclidean')\n```\n:::\n\n\nThe code chunk below can then be used to list the content of `proxmat` for visual inspection. As the full list by township is long, we will not display it here and you can try it yourself. :)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproxmat\n```\n:::\n\n\n### 7.7. Computing Hierarchical Clustering\n\nIn R, there are several packages provide hierarchical clustering function. In this hands-on exercise, [*hclust()*](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/hclust.html) of **R stats** will be used.\n\n*hclust()* employed agglomeration method to compute the cluster. Eight clustering algorithms are supported, they are: `ward.D`, `ward.D2`, `single, complete`, `average(UPGMA)`, `mcquitty(WPGMA)`, `median(WPGMC)` and `centroid(UPGMC)`.\n\nThe code chunk below performs hierarchical cluster analysis using `ward.D` method. The hierarchical clustering output is stored in an object of class **hclust** which describes the tree produced by the clustering process.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhclust_ward <- hclust(proxmat, method = 'ward.D')\n```\n:::\n\n\nWe can then plot the tree by using *plot()* of **R Graphics** as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hclust_ward, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### 7.8. Selecting the Optimal Clustering Algorithm\n\nOne of the challenge in performing hierarchical clustering is to identify stronger clustering structures. The issue can be solved by using use [*agnes()*](https://www.rdocumentation.org/packages/cluster/versions/2.1.0/topics/agnes) function of [**cluster**](https://cran.r-project.org/web/packages/cluster/) package. It functions like *hclus()*, however, with the *agnes()* function you can also get the agglomerative coefficient, which measures the amount of clustering structure found (values closer to 1 suggest strong clustering structure).\n\nThe code chunk below will be used to compute the agglomerative coefficients of all hierarchical clustering algorithms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- c( \"average\", \"single\", \"complete\", \"ward\")\nnames(m) <- c( \"average\", \"single\", \"complete\", \"ward\")\n\nac <- function(x) {\n  agnes(shan_ict, method = x)$ac\n}\n\nmap_dbl(m, ac)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  average    single  complete      ward \n0.8131144 0.6628705 0.8950702 0.9427730 \n```\n:::\n:::\n\n\nWith reference to the output above, we can see that Ward's method provides the strongest clustering structure among the four methods assessed. Hence, in the subsequent analysis, only Ward's method will be used.\n\n### 7.9. Determining Optimal Clusters\n\nAnother technical challenge face by data analyst in performing clustering analysis is to determine the optimal clusters to retain.\n\nThere are [three](https://www.datanovia.com/en/lessons/determining-the-optimal-number-of-clusters-3-must-know-methods/) commonly used methods to determine the optimal clusters, they are:\n\n-   [Elbow Method](https://en.wikipedia.org/wiki/Elbow_method_(clustering))\n\n-   [Average Silhouette Method](https://www.sciencedirect.com/science/article/pii/0377042787901257?via%3Dihub)\n\n-   [Gap Statistic Method](https://statweb.stanford.edu/~gwalther/gap)\n\n#### Gap Statistic Method\n\nThe [**gap statistic**](http://www.web.stanford.edu/~hastie/Papers/gap.pdf) compares the total within intra-cluster variation for different values of k with their expected values under null reference distribution of the data. The estimate of the optimal clusters will be value that maximize the gap statistic (i.e., that yields the largest gap statistic). This means that the clustering structure is far away from the random uniform distribution of points.\n\nTo compute the gap statistic, [*clusGap()*](https://www.rdocumentation.org/packages/cluster/versions/2.1.0/topics/clusGap) of [**cluster**](https://cran.r-project.org/web/packages/cluster/) package will be used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngap_stat <- clusGap(shan_ict, \n                    FUN = hcut, \n                    nstart = 25, \n                    K.max = 10, \n                    B = 50)\n# Print the result\nprint(gap_stat, method = \"firstmax\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nClustering Gap statistic [\"clusGap\"] from call:\nclusGap(x = shan_ict, FUNcluster = hcut, K.max = 10, B = 50, nstart = 25)\nB=50 simulated reference sets, k = 1..10; spaceH0=\"scaledPCA\"\n --> Number of clusters (method 'firstmax'): 1\n          logW   E.logW       gap     SE.sim\n [1,] 8.407129 8.677830 0.2707006 0.03692273\n [2,] 8.130029 8.346462 0.2164322 0.04088387\n [3,] 7.992265 8.200253 0.2079877 0.03762167\n [4,] 7.862224 8.079170 0.2169462 0.04018998\n [5,] 7.756461 7.977981 0.2215201 0.04229538\n [6,] 7.665594 7.890134 0.2245409 0.04501316\n [7,] 7.590919 7.812990 0.2220709 0.04364077\n [8,] 7.526680 7.739537 0.2128575 0.04477188\n [9,] 7.458024 7.670476 0.2124519 0.04623855\n[10,] 7.377412 7.603947 0.2265346 0.04762720\n```\n:::\n:::\n\n\nAlso note that the [*hcut*](https://rpkgs.datanovia.com/factoextra/reference/hcut.html) function used is from [**factoextra**](https://rpkgs.datanovia.com/factoextra/) package.\n\nNext, we can visualise the plot by using [*fviz_gap_stat()*](https://rpkgs.datanovia.com/factoextra/reference/fviz_nbclust.html) of [**factoextra**](https://rpkgs.datanovia.com/factoextra/) package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_gap_stat(gap_stat)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nWith reference to the gap statistic graph above, the recommended number of cluster to retain is 1. However, it is not logical to retain only one cluster. By examine the gap statistic graph, the 6-cluster gives the largest gap statistic and should be the next best cluster to pick.\n\n**Note:** In addition to these commonly used approaches, the [NbClust](https://cran.r-project.org/web/packages/NbClust/) package, published by Charrad et al., 2014, provides 30 indices for determining the relevant number of clusters and proposes to users the best clustering scheme from the different results obtained by varying all combinations of number of clusters, distance measures, and clustering methods.\n\n### 7.10. Interpreting the dendrograms\n\nIn the dendrogram displayed above, each leaf corresponds to one observation. As we move up the tree, observations that are similar to each other are combined into branches, which are themselves fused at a higher height.\n\nThe height of the fusion, provided on the vertical axis, indicates the (dis)similarity between two observations. The higher the height of the fusion, the less similar the observations are. Note that, conclusions about the proximity of two observations can be drawn only based on the height where branches containing those two observations first are fused. We cannot use the proximity of two observations along the horizontal axis as a criteria of their similarity.\n\nIt's also possible to draw the dendrogram with a border around the selected clusters by using [*rect.hclust()*](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/rect.hclust.html) of **R stats**. The argument `border` is used to specify the border colors for the rectangles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hclust_ward, cex = 0.6)\nrect.hclust(hclust_ward, \n            k = 6, \n            border = 2:5)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n### 7.11. Visually-driven hierarchical clustering analysis\n\nIn this section, we will learn how to perform visually-driven hiearchical clustering analysis by using [**heatmaply**](https://cran.r-project.org/web/packages/heatmaply/) package.\n\nWith **heatmaply**, we are able to build both highly interactive cluster heatmap or static cluster heatmap.\n\n### 7.12. Transforming the data frame into a matrix\n\nThe data was loaded into a data frame, but it has to be a data matrix to make your heatmap.\n\nThe code chunk below will be used to transform `shan_ict` data frame into a data matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict_mat <- data.matrix(shan_ict)\n```\n:::\n\n\n### 7.13. Plotting interactive cluster heatmap using *heatmaply()*\n\nIn the code chunk below, the [*heatmaply()*](https://talgalili.github.io/heatmaply/reference/heatmaply.html) of [heatmaply](https://talgalili.github.io/heatmaply/) package is used to build an interactive cluster heatmap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmaply(normalize(shan_ict_mat),\n          Colv=NA,\n          dist_method = \"euclidean\",\n          hclust_method = \"ward.D\",\n          seriate = \"OLO\",\n          colors = Blues,\n          k_row = 6,\n          margins = c(NA,200,60,NA),\n          fontsize_row = 4,\n          fontsize_col = 5,\n          main=\"Geographic Segmentation of Shan State by ICT indicators\",\n          xlab = \"ICT Indicators\",\n          ylab = \"Townships of Shan State\"\n          )\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-9eceb20dc2a931752ae4\" style=\"width:100%;height:464px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9eceb20dc2a931752ae4\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5],\"y\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55],\"z\":[[0.116978282802357,0.129468002916701,0.22051676674467,0.384613999201764,0],[0.119071471357574,0.345093075355747,0.146680718622619,0.689156011292375,0.0306923094501804],[0.448112949126574,0.552259924114501,0.105215687600081,0.574129014267529,0.484807392774743],[0.394726524387261,0.646477338669936,0.19477119473094,0.398016081357507,0.307033923303471],[0.409738609943887,0.667785462581825,0.205939628052291,0.480784254803859,0.310457200410047],[0.560359050607694,0.682160053201915,0.219828980006303,0.532717729177229,0.295696949383387],[0.509783518401058,0.705849662481414,0.235277615529988,0.56572881621916,0.184217142327857],[0.445367826108455,0.648475186589583,0.400725374496756,0.525729584351687,0.325727661622098],[0.303006324046602,0.491472190827421,0.393413634291369,0.434988683676573,0.25539117902522],[0.285460565623123,0.653167734189465,0.351129977629807,0.321903369400093,0.274683722730117],[0.186896495593756,0.473621686944799,0.177547109767516,0.219017992119371,0.219238039033904],[0.262948885760044,0.600934420551276,0.105588681661233,0.309844721395711,0.32244406175046],[0.348384569046878,0.550413307218695,0.0132133117776572,0.330600515260223,0.280505026346822],[0.372116151704965,0.374968621142249,0.125060804628556,0.363502861923713,0.208286637250586],[0.382049084643175,0.495293243751349,0.165281214256075,0.332852029421132,0.126911060390332],[0.398090757930385,0.467734047728609,0.165251926083381,0.248272216763125,0.125663315216338],[0.463675071811737,0.480273489712105,0.0495176036018547,0.278454014117194,0.102240256271893],[0.454391396013767,0.585943534900779,0.144172529109699,0.304817572789695,0.117641144346071],[0.572059422162612,0.603028579702235,0.18200927177224,0.320846100415741,0.0996532209950878],[0.64202483918062,0.577864390148239,0.207338745441228,0.255258118966462,0.176074057695434],[0.469637019864802,0.49275331606036,0.336403906718691,0.326463285635126,0.199643002704722],[0.472437575771037,0.708306581316802,0.181528926899385,0.0981964513254065,0.186836974506664],[0.487021825059319,0.536184545909484,0.1623692849231,0.155474604691974,0.0744963103413769],[0.534163143993451,0.455760556744961,0.109548536966956,0.076155538926932,0.106925771850934],[0.437590296823069,0.464204461437082,0.110874787457869,0.0984403758574017,0.0985978869506665],[0.452636675796627,0.377797614010294,0.113655496814988,0.0877697005887191,0.0640685752289788],[0.318011520183019,0.341693315696117,0.0982231808523387,0.141213400161106,0.0684535703034676],[0.303905626461184,0.295734660011411,0.122161422028907,0.220797228887767,0.0933576373559664],[0.125839377932289,0.271665869542777,0.146912934029539,0.111904436916593,0.0401203752296987],[0.1648181386917,0.163070599120654,0,0,0.050562923174398],[0.292778031055123,0,0.0180206673088627,0.0205146898168363,0.0573419602932674],[0.373857483778625,0.0995290076456667,0.0295999006447705,0.0262900696870936,0.00411244014094081],[0.481303842133627,0.142297506536797,0.0316650514783228,0.0125730639984617,0.030854020566576],[1,0.198958169425964,0.0512340297746273,0.119978472699803,0.0127547808735244],[0.855314778071882,0.535580295292678,0.0954404378234391,0.180215108968874,0.107759971325446],[0.789802194306684,0.707463556363309,0.160787084615829,0.406501651460893,0.207451038928221],[0.653022272989167,0.603518277436298,0.0907572048090615,0.450320578796944,0.139286867591449],[0.708316665856044,0.59451431070864,0.199599204123416,0.410008712407441,0.140105344905725],[0.828481634580948,0.533096150331035,0.222253044854804,0.49414581896158,0.245321426698747],[0.924414874434519,0.815706630141315,0.391551407290058,0.509561826896415,0.147799896773415],[0.554582082266574,0.857899290321775,0.667007964836916,0.411501854757207,0.135186676818821],[0.217633980358742,0.65209843040106,1,0.287788284692333,0.196437751553831],[0,0.23543567048956,0.932101354458042,0.401015569024513,0.0844217926569466],[0.109374929636258,0.623942179795541,0.622050632093838,0.618872994218249,0.107369754921389],[0.213613705288465,0.545980181296846,0.462858065656792,0.555883136314662,0.089979971244949],[0.229897462083034,0.606803420347241,0.441880181094265,0.645581402670746,0.238387780704064],[0.245824811756765,0.739869228579844,0.49811595358599,0.801230600000326,0.301658910303963],[0.0694967457544946,0.911879045679933,0.736263645750856,0.973268306969539,0.362172608061988],[0.131890106624229,0.766915045456103,0.471174055309928,0.742030952777324,0.665568016626695],[0.164829658497982,0.515216701198681,0.334570254727253,0.578557341817938,0.529033034945849],[0.531763581261236,0.718177853098515,0.338119112137043,0.645068858125427,0.496659923518642],[0.463214009841455,0.777367942019409,0.357599483272661,0.611463125655814,0.638873044291007],[0.742781450226171,0.879882415822816,0.440755998903745,0.787178952652566,0.873978634377844],[0.73856184642803,0.885602038677547,0.318801655583425,1,1],[0.334059480538155,1,0.765345298573847,0.967808669559975,0.987566110737814]],\"text\":[[\"row: Narphan<br>column: RADIO_PR<br>value: 0.116978\",\"row: Narphan<br>column: TV_PR<br>value: 0.129468\",\"row: Narphan<br>column: LLPHONE_PR<br>value: 0.220517\",\"row: Narphan<br>column: MPHONE_PR<br>value: 0.384614\",\"row: Narphan<br>column: COMPUTER_PR<br>value: 0.000000\"],[\"row: Pangwaun<br>column: RADIO_PR<br>value: 0.119071\",\"row: Pangwaun<br>column: TV_PR<br>value: 0.345093\",\"row: Pangwaun<br>column: LLPHONE_PR<br>value: 0.146681\",\"row: Pangwaun<br>column: MPHONE_PR<br>value: 0.689156\",\"row: Pangwaun<br>column: COMPUTER_PR<br>value: 0.030692\"],[\"row: Mongpan<br>column: RADIO_PR<br>value: 0.448113\",\"row: Mongpan<br>column: TV_PR<br>value: 0.552260\",\"row: Mongpan<br>column: LLPHONE_PR<br>value: 0.105216\",\"row: Mongpan<br>column: MPHONE_PR<br>value: 0.574129\",\"row: Mongpan<br>column: COMPUTER_PR<br>value: 0.484807\"],[\"row: Nansang<br>column: RADIO_PR<br>value: 0.394727\",\"row: Nansang<br>column: TV_PR<br>value: 0.646477\",\"row: Nansang<br>column: LLPHONE_PR<br>value: 0.194771\",\"row: Nansang<br>column: MPHONE_PR<br>value: 0.398016\",\"row: Nansang<br>column: COMPUTER_PR<br>value: 0.307034\"],[\"row: Kyaukme<br>column: RADIO_PR<br>value: 0.409739\",\"row: Kyaukme<br>column: TV_PR<br>value: 0.667785\",\"row: Kyaukme<br>column: LLPHONE_PR<br>value: 0.205940\",\"row: Kyaukme<br>column: MPHONE_PR<br>value: 0.480784\",\"row: Kyaukme<br>column: COMPUTER_PR<br>value: 0.310457\"],[\"row: Kalaw<br>column: RADIO_PR<br>value: 0.560359\",\"row: Kalaw<br>column: TV_PR<br>value: 0.682160\",\"row: Kalaw<br>column: LLPHONE_PR<br>value: 0.219829\",\"row: Kalaw<br>column: MPHONE_PR<br>value: 0.532718\",\"row: Kalaw<br>column: COMPUTER_PR<br>value: 0.295697\"],[\"row: Hseni<br>column: RADIO_PR<br>value: 0.509784\",\"row: Hseni<br>column: TV_PR<br>value: 0.705850\",\"row: Hseni<br>column: LLPHONE_PR<br>value: 0.235278\",\"row: Hseni<br>column: MPHONE_PR<br>value: 0.565729\",\"row: Hseni<br>column: COMPUTER_PR<br>value: 0.184217\"],[\"row: Langkho<br>column: RADIO_PR<br>value: 0.445368\",\"row: Langkho<br>column: TV_PR<br>value: 0.648475\",\"row: Langkho<br>column: LLPHONE_PR<br>value: 0.400725\",\"row: Langkho<br>column: MPHONE_PR<br>value: 0.525730\",\"row: Langkho<br>column: COMPUTER_PR<br>value: 0.325728\"],[\"row: Kunhing<br>column: RADIO_PR<br>value: 0.303006\",\"row: Kunhing<br>column: TV_PR<br>value: 0.491472\",\"row: Kunhing<br>column: LLPHONE_PR<br>value: 0.393414\",\"row: Kunhing<br>column: MPHONE_PR<br>value: 0.434989\",\"row: Kunhing<br>column: COMPUTER_PR<br>value: 0.255391\"],[\"row: Laihka<br>column: RADIO_PR<br>value: 0.285461\",\"row: Laihka<br>column: TV_PR<br>value: 0.653168\",\"row: Laihka<br>column: LLPHONE_PR<br>value: 0.351130\",\"row: Laihka<br>column: MPHONE_PR<br>value: 0.321903\",\"row: Laihka<br>column: COMPUTER_PR<br>value: 0.274684\"],[\"row: Monghsat<br>column: RADIO_PR<br>value: 0.186896\",\"row: Monghsat<br>column: TV_PR<br>value: 0.473622\",\"row: Monghsat<br>column: LLPHONE_PR<br>value: 0.177547\",\"row: Monghsat<br>column: MPHONE_PR<br>value: 0.219018\",\"row: Monghsat<br>column: COMPUTER_PR<br>value: 0.219238\"],[\"row: Loilen<br>column: RADIO_PR<br>value: 0.262949\",\"row: Loilen<br>column: TV_PR<br>value: 0.600934\",\"row: Loilen<br>column: LLPHONE_PR<br>value: 0.105589\",\"row: Loilen<br>column: MPHONE_PR<br>value: 0.309845\",\"row: Loilen<br>column: COMPUTER_PR<br>value: 0.322444\"],[\"row: Mongnai<br>column: RADIO_PR<br>value: 0.348385\",\"row: Mongnai<br>column: TV_PR<br>value: 0.550413\",\"row: Mongnai<br>column: LLPHONE_PR<br>value: 0.013213\",\"row: Mongnai<br>column: MPHONE_PR<br>value: 0.330601\",\"row: Mongnai<br>column: COMPUTER_PR<br>value: 0.280505\"],[\"row: Mongton<br>column: RADIO_PR<br>value: 0.372116\",\"row: Mongton<br>column: TV_PR<br>value: 0.374969\",\"row: Mongton<br>column: LLPHONE_PR<br>value: 0.125061\",\"row: Mongton<br>column: MPHONE_PR<br>value: 0.363503\",\"row: Mongton<br>column: COMPUTER_PR<br>value: 0.208287\"],[\"row: Hsipaw<br>column: RADIO_PR<br>value: 0.382049\",\"row: Hsipaw<br>column: TV_PR<br>value: 0.495293\",\"row: Hsipaw<br>column: LLPHONE_PR<br>value: 0.165281\",\"row: Hsipaw<br>column: MPHONE_PR<br>value: 0.332852\",\"row: Hsipaw<br>column: COMPUTER_PR<br>value: 0.126911\"],[\"row: Hopong<br>column: RADIO_PR<br>value: 0.398091\",\"row: Hopong<br>column: TV_PR<br>value: 0.467734\",\"row: Hopong<br>column: LLPHONE_PR<br>value: 0.165252\",\"row: Hopong<br>column: MPHONE_PR<br>value: 0.248272\",\"row: Hopong<br>column: COMPUTER_PR<br>value: 0.125663\"],[\"row: Monghsu<br>column: RADIO_PR<br>value: 0.463675\",\"row: Monghsu<br>column: TV_PR<br>value: 0.480273\",\"row: Monghsu<br>column: LLPHONE_PR<br>value: 0.049518\",\"row: Monghsu<br>column: MPHONE_PR<br>value: 0.278454\",\"row: Monghsu<br>column: COMPUTER_PR<br>value: 0.102240\"],[\"row: Pinlaung<br>column: RADIO_PR<br>value: 0.454391\",\"row: Pinlaung<br>column: TV_PR<br>value: 0.585944\",\"row: Pinlaung<br>column: LLPHONE_PR<br>value: 0.144173\",\"row: Pinlaung<br>column: MPHONE_PR<br>value: 0.304818\",\"row: Pinlaung<br>column: COMPUTER_PR<br>value: 0.117641\"],[\"row: Mongmit<br>column: RADIO_PR<br>value: 0.572059\",\"row: Mongmit<br>column: TV_PR<br>value: 0.603029\",\"row: Mongmit<br>column: LLPHONE_PR<br>value: 0.182009\",\"row: Mongmit<br>column: MPHONE_PR<br>value: 0.320846\",\"row: Mongmit<br>column: COMPUTER_PR<br>value: 0.099653\"],[\"row: Pekon<br>column: RADIO_PR<br>value: 0.642025\",\"row: Pekon<br>column: TV_PR<br>value: 0.577864\",\"row: Pekon<br>column: LLPHONE_PR<br>value: 0.207339\",\"row: Pekon<br>column: MPHONE_PR<br>value: 0.255258\",\"row: Pekon<br>column: COMPUTER_PR<br>value: 0.176074\"],[\"row: Kutkai<br>column: RADIO_PR<br>value: 0.469637\",\"row: Kutkai<br>column: TV_PR<br>value: 0.492753\",\"row: Kutkai<br>column: LLPHONE_PR<br>value: 0.336404\",\"row: Kutkai<br>column: MPHONE_PR<br>value: 0.326463\",\"row: Kutkai<br>column: COMPUTER_PR<br>value: 0.199643\"],[\"row: Namtu<br>column: RADIO_PR<br>value: 0.472438\",\"row: Namtu<br>column: TV_PR<br>value: 0.708307\",\"row: Namtu<br>column: LLPHONE_PR<br>value: 0.181529\",\"row: Namtu<br>column: MPHONE_PR<br>value: 0.098196\",\"row: Namtu<br>column: COMPUTER_PR<br>value: 0.186837\"],[\"row: Hsihseng<br>column: RADIO_PR<br>value: 0.487022\",\"row: Hsihseng<br>column: TV_PR<br>value: 0.536185\",\"row: Hsihseng<br>column: LLPHONE_PR<br>value: 0.162369\",\"row: Hsihseng<br>column: MPHONE_PR<br>value: 0.155475\",\"row: Hsihseng<br>column: COMPUTER_PR<br>value: 0.074496\"],[\"row: Kyethi<br>column: RADIO_PR<br>value: 0.534163\",\"row: Kyethi<br>column: TV_PR<br>value: 0.455761\",\"row: Kyethi<br>column: LLPHONE_PR<br>value: 0.109549\",\"row: Kyethi<br>column: MPHONE_PR<br>value: 0.076156\",\"row: Kyethi<br>column: COMPUTER_PR<br>value: 0.106926\"],[\"row: Tangyan<br>column: RADIO_PR<br>value: 0.437590\",\"row: Tangyan<br>column: TV_PR<br>value: 0.464204\",\"row: Tangyan<br>column: LLPHONE_PR<br>value: 0.110875\",\"row: Tangyan<br>column: MPHONE_PR<br>value: 0.098440\",\"row: Tangyan<br>column: COMPUTER_PR<br>value: 0.098598\"],[\"row: Namhsan<br>column: RADIO_PR<br>value: 0.452637\",\"row: Namhsan<br>column: TV_PR<br>value: 0.377798\",\"row: Namhsan<br>column: LLPHONE_PR<br>value: 0.113655\",\"row: Namhsan<br>column: MPHONE_PR<br>value: 0.087770\",\"row: Namhsan<br>column: COMPUTER_PR<br>value: 0.064069\"],[\"row: Mongyai<br>column: RADIO_PR<br>value: 0.318012\",\"row: Mongyai<br>column: TV_PR<br>value: 0.341693\",\"row: Mongyai<br>column: LLPHONE_PR<br>value: 0.098223\",\"row: Mongyai<br>column: MPHONE_PR<br>value: 0.141213\",\"row: Mongyai<br>column: COMPUTER_PR<br>value: 0.068454\"],[\"row: Mongping<br>column: RADIO_PR<br>value: 0.303906\",\"row: Mongping<br>column: TV_PR<br>value: 0.295735\",\"row: Mongping<br>column: LLPHONE_PR<br>value: 0.122161\",\"row: Mongping<br>column: MPHONE_PR<br>value: 0.220797\",\"row: Mongping<br>column: COMPUTER_PR<br>value: 0.093358\"],[\"row: Mongkhet<br>column: RADIO_PR<br>value: 0.125839\",\"row: Mongkhet<br>column: TV_PR<br>value: 0.271666\",\"row: Mongkhet<br>column: LLPHONE_PR<br>value: 0.146913\",\"row: Mongkhet<br>column: MPHONE_PR<br>value: 0.111904\",\"row: Mongkhet<br>column: COMPUTER_PR<br>value: 0.040120\"],[\"row: Mawkmai<br>column: RADIO_PR<br>value: 0.164818\",\"row: Mawkmai<br>column: TV_PR<br>value: 0.163071\",\"row: Mawkmai<br>column: LLPHONE_PR<br>value: 0.000000\",\"row: Mawkmai<br>column: MPHONE_PR<br>value: 0.000000\",\"row: Mawkmai<br>column: COMPUTER_PR<br>value: 0.050563\"],[\"row: Mongkaing<br>column: RADIO_PR<br>value: 0.292778\",\"row: Mongkaing<br>column: TV_PR<br>value: 0.000000\",\"row: Mongkaing<br>column: LLPHONE_PR<br>value: 0.018021\",\"row: Mongkaing<br>column: MPHONE_PR<br>value: 0.020515\",\"row: Mongkaing<br>column: COMPUTER_PR<br>value: 0.057342\"],[\"row: Manton<br>column: RADIO_PR<br>value: 0.373857\",\"row: Manton<br>column: TV_PR<br>value: 0.099529\",\"row: Manton<br>column: LLPHONE_PR<br>value: 0.029600\",\"row: Manton<br>column: MPHONE_PR<br>value: 0.026290\",\"row: Manton<br>column: COMPUTER_PR<br>value: 0.004112\"],[\"row: Matman<br>column: RADIO_PR<br>value: 0.481304\",\"row: Matman<br>column: TV_PR<br>value: 0.142298\",\"row: Matman<br>column: LLPHONE_PR<br>value: 0.031665\",\"row: Matman<br>column: MPHONE_PR<br>value: 0.012573\",\"row: Matman<br>column: COMPUTER_PR<br>value: 0.030854\"],[\"row: Ywangan<br>column: RADIO_PR<br>value: 1.000000\",\"row: Ywangan<br>column: TV_PR<br>value: 0.198958\",\"row: Ywangan<br>column: LLPHONE_PR<br>value: 0.051234\",\"row: Ywangan<br>column: MPHONE_PR<br>value: 0.119978\",\"row: Ywangan<br>column: COMPUTER_PR<br>value: 0.012755\"],[\"row: Pindaya<br>column: RADIO_PR<br>value: 0.855315\",\"row: Pindaya<br>column: TV_PR<br>value: 0.535580\",\"row: Pindaya<br>column: LLPHONE_PR<br>value: 0.095440\",\"row: Pindaya<br>column: MPHONE_PR<br>value: 0.180215\",\"row: Pindaya<br>column: COMPUTER_PR<br>value: 0.107760\"],[\"row: Lawksawk<br>column: RADIO_PR<br>value: 0.789802\",\"row: Lawksawk<br>column: TV_PR<br>value: 0.707464\",\"row: Lawksawk<br>column: LLPHONE_PR<br>value: 0.160787\",\"row: Lawksawk<br>column: MPHONE_PR<br>value: 0.406502\",\"row: Lawksawk<br>column: COMPUTER_PR<br>value: 0.207451\"],[\"row: Nyaungshwe<br>column: RADIO_PR<br>value: 0.653022\",\"row: Nyaungshwe<br>column: TV_PR<br>value: 0.603518\",\"row: Nyaungshwe<br>column: LLPHONE_PR<br>value: 0.090757\",\"row: Nyaungshwe<br>column: MPHONE_PR<br>value: 0.450321\",\"row: Nyaungshwe<br>column: COMPUTER_PR<br>value: 0.139287\"],[\"row: Nawnghkio<br>column: RADIO_PR<br>value: 0.708317\",\"row: Nawnghkio<br>column: TV_PR<br>value: 0.594514\",\"row: Nawnghkio<br>column: LLPHONE_PR<br>value: 0.199599\",\"row: Nawnghkio<br>column: MPHONE_PR<br>value: 0.410009\",\"row: Nawnghkio<br>column: COMPUTER_PR<br>value: 0.140105\"],[\"row: Monghpyak<br>column: RADIO_PR<br>value: 0.828482\",\"row: Monghpyak<br>column: TV_PR<br>value: 0.533096\",\"row: Monghpyak<br>column: LLPHONE_PR<br>value: 0.222253\",\"row: Monghpyak<br>column: MPHONE_PR<br>value: 0.494146\",\"row: Monghpyak<br>column: COMPUTER_PR<br>value: 0.245321\"],[\"row: Mabein<br>column: RADIO_PR<br>value: 0.924415\",\"row: Mabein<br>column: TV_PR<br>value: 0.815707\",\"row: Mabein<br>column: LLPHONE_PR<br>value: 0.391551\",\"row: Mabein<br>column: MPHONE_PR<br>value: 0.509562\",\"row: Mabein<br>column: COMPUTER_PR<br>value: 0.147800\"],[\"row: Mongyawng<br>column: RADIO_PR<br>value: 0.554582\",\"row: Mongyawng<br>column: TV_PR<br>value: 0.857899\",\"row: Mongyawng<br>column: LLPHONE_PR<br>value: 0.667008\",\"row: Mongyawng<br>column: MPHONE_PR<br>value: 0.411502\",\"row: Mongyawng<br>column: COMPUTER_PR<br>value: 0.135187\"],[\"row: Kunlong<br>column: RADIO_PR<br>value: 0.217634\",\"row: Kunlong<br>column: TV_PR<br>value: 0.652098\",\"row: Kunlong<br>column: LLPHONE_PR<br>value: 1.000000\",\"row: Kunlong<br>column: MPHONE_PR<br>value: 0.287788\",\"row: Kunlong<br>column: COMPUTER_PR<br>value: 0.196438\"],[\"row: Konkyan<br>column: RADIO_PR<br>value: 0.000000\",\"row: Konkyan<br>column: TV_PR<br>value: 0.235436\",\"row: Konkyan<br>column: LLPHONE_PR<br>value: 0.932101\",\"row: Konkyan<br>column: MPHONE_PR<br>value: 0.401016\",\"row: Konkyan<br>column: COMPUTER_PR<br>value: 0.084422\"],[\"row: Mongyang<br>column: RADIO_PR<br>value: 0.109375\",\"row: Mongyang<br>column: TV_PR<br>value: 0.623942\",\"row: Mongyang<br>column: LLPHONE_PR<br>value: 0.622051\",\"row: Mongyang<br>column: MPHONE_PR<br>value: 0.618873\",\"row: Mongyang<br>column: COMPUTER_PR<br>value: 0.107370\"],[\"row: Mongmao<br>column: RADIO_PR<br>value: 0.213614\",\"row: Mongmao<br>column: TV_PR<br>value: 0.545980\",\"row: Mongmao<br>column: LLPHONE_PR<br>value: 0.462858\",\"row: Mongmao<br>column: MPHONE_PR<br>value: 0.555883\",\"row: Mongmao<br>column: COMPUTER_PR<br>value: 0.089980\"],[\"row: Hopang<br>column: RADIO_PR<br>value: 0.229897\",\"row: Hopang<br>column: TV_PR<br>value: 0.606803\",\"row: Hopang<br>column: LLPHONE_PR<br>value: 0.441880\",\"row: Hopang<br>column: MPHONE_PR<br>value: 0.645581\",\"row: Hopang<br>column: COMPUTER_PR<br>value: 0.238388\"],[\"row: Namhkan<br>column: RADIO_PR<br>value: 0.245825\",\"row: Namhkan<br>column: TV_PR<br>value: 0.739869\",\"row: Namhkan<br>column: LLPHONE_PR<br>value: 0.498116\",\"row: Namhkan<br>column: MPHONE_PR<br>value: 0.801231\",\"row: Namhkan<br>column: COMPUTER_PR<br>value: 0.301659\"],[\"row: Laukkaing<br>column: RADIO_PR<br>value: 0.069497\",\"row: Laukkaing<br>column: TV_PR<br>value: 0.911879\",\"row: Laukkaing<br>column: LLPHONE_PR<br>value: 0.736264\",\"row: Laukkaing<br>column: MPHONE_PR<br>value: 0.973268\",\"row: Laukkaing<br>column: COMPUTER_PR<br>value: 0.362173\"],[\"row: Mongla<br>column: RADIO_PR<br>value: 0.131890\",\"row: Mongla<br>column: TV_PR<br>value: 0.766915\",\"row: Mongla<br>column: LLPHONE_PR<br>value: 0.471174\",\"row: Mongla<br>column: MPHONE_PR<br>value: 0.742031\",\"row: Mongla<br>column: COMPUTER_PR<br>value: 0.665568\"],[\"row: Pangsang<br>column: RADIO_PR<br>value: 0.164830\",\"row: Pangsang<br>column: TV_PR<br>value: 0.515217\",\"row: Pangsang<br>column: LLPHONE_PR<br>value: 0.334570\",\"row: Pangsang<br>column: MPHONE_PR<br>value: 0.578557\",\"row: Pangsang<br>column: COMPUTER_PR<br>value: 0.529033\"],[\"row: Kengtung<br>column: RADIO_PR<br>value: 0.531764\",\"row: Kengtung<br>column: TV_PR<br>value: 0.718178\",\"row: Kengtung<br>column: LLPHONE_PR<br>value: 0.338119\",\"row: Kengtung<br>column: MPHONE_PR<br>value: 0.645069\",\"row: Kengtung<br>column: COMPUTER_PR<br>value: 0.496660\"],[\"row: Lashio<br>column: RADIO_PR<br>value: 0.463214\",\"row: Lashio<br>column: TV_PR<br>value: 0.777368\",\"row: Lashio<br>column: LLPHONE_PR<br>value: 0.357599\",\"row: Lashio<br>column: MPHONE_PR<br>value: 0.611463\",\"row: Lashio<br>column: COMPUTER_PR<br>value: 0.638873\"],[\"row: Taunggyi<br>column: RADIO_PR<br>value: 0.742781\",\"row: Taunggyi<br>column: TV_PR<br>value: 0.879882\",\"row: Taunggyi<br>column: LLPHONE_PR<br>value: 0.440756\",\"row: Taunggyi<br>column: MPHONE_PR<br>value: 0.787179\",\"row: Taunggyi<br>column: COMPUTER_PR<br>value: 0.873979\"],[\"row: Tachileik<br>column: RADIO_PR<br>value: 0.738562\",\"row: Tachileik<br>column: TV_PR<br>value: 0.885602\",\"row: Tachileik<br>column: LLPHONE_PR<br>value: 0.318802\",\"row: Tachileik<br>column: MPHONE_PR<br>value: 1.000000\",\"row: Tachileik<br>column: COMPUTER_PR<br>value: 1.000000\"],[\"row: Muse<br>column: RADIO_PR<br>value: 0.334059\",\"row: Muse<br>column: TV_PR<br>value: 1.000000\",\"row: Muse<br>column: LLPHONE_PR<br>value: 0.765345\",\"row: Muse<br>column: MPHONE_PR<br>value: 0.967809\",\"row: Muse<br>column: COMPUTER_PR<br>value: 0.987566\"]],\"colorscale\":[[0,\"#F7FBFF\"],[0.00411244014094081,\"#F6FAFE\"],[0.0125730639984617,\"#F4F9FE\"],[0.0127547808735244,\"#F4F9FE\"],[0.0132133117776572,\"#F4F9FE\"],[0.0180206673088627,\"#F3F8FD\"],[0.0205146898168363,\"#F3F8FD\"],[0.0262900696870936,\"#F1F7FD\"],[0.0295999006447705,\"#F0F6FC\"],[0.0306923094501804,\"#F0F6FC\"],[0.030854020566576,\"#F0F6FC\"],[0.0316650514783228,\"#F0F6FC\"],[0.0401203752296987,\"#EFF5FC\"],[0.0495176036018547,\"#ECF4FB\"],[0.050562923174398,\"#ECF4FB\"],[0.0512340297746273,\"#ECF4FB\"],[0.0573419602932674,\"#EBF3FB\"],[0.0640685752289788,\"#EAF2FA\"],[0.0684535703034676,\"#E9F2FA\"],[0.0694967457544946,\"#E8F1FA\"],[0.0744963103413769,\"#E8F1FA\"],[0.076155538926932,\"#E8F1FA\"],[0.0844217926569466,\"#E5EFF9\"],[0.0877697005887191,\"#E5EFF9\"],[0.089979971244949,\"#E4EFF9\"],[0.0907572048090615,\"#E4EFF9\"],[0.0933576373559664,\"#E4EEF8\"],[0.0954404378234391,\"#E4EEF8\"],[0.0981964513254065,\"#E3EEF8\"],[0.0982231808523387,\"#E3EEF8\"],[0.0984403758574017,\"#E3EEF8\"],[0.0985978869506665,\"#E3EEF8\"],[0.0995290076456667,\"#E3EEF8\"],[0.0996532209950878,\"#E3EEF8\"],[0.102240256271893,\"#E2EDF8\"],[0.105215687600081,\"#E1EDF8\"],[0.105588681661233,\"#E1EDF8\"],[0.106925771850934,\"#E1EDF8\"],[0.107369754921389,\"#E1EDF8\"],[0.107759971325446,\"#E1EDF8\"],[0.109374929636258,\"#E1ECF7\"],[0.109548536966956,\"#E1ECF7\"],[0.110874787457869,\"#E1ECF7\"],[0.111904436916593,\"#E0ECF7\"],[0.113655496814988,\"#E0ECF7\"],[0.116978282802357,\"#DFEBF7\"],[0.117641144346071,\"#DFEBF7\"],[0.119071471357574,\"#DFEBF7\"],[0.119978472699803,\"#DEEBF7\"],[0.122161422028907,\"#DEEBF7\"],[0.125060804628556,\"#DDEAF6\"],[0.125663315216338,\"#DDEAF6\"],[0.125839377932289,\"#DDEAF6\"],[0.126911060390332,\"#DDEAF6\"],[0.129468002916701,\"#DDEAF6\"],[0.131890106624229,\"#DCE9F6\"],[0.135186676818821,\"#DCE9F6\"],[0.139286867591449,\"#DAE8F5\"],[0.140105344905725,\"#DAE8F5\"],[0.141213400161106,\"#DAE8F5\"],[0.142297506536797,\"#DAE8F5\"],[0.144172529109699,\"#DAE8F5\"],[0.146680718622619,\"#DAE8F5\"],[0.146912934029539,\"#DAE8F5\"],[0.147799896773415,\"#D9E7F5\"],[0.155474604691974,\"#D7E6F4\"],[0.160787084615829,\"#D7E6F4\"],[0.1623692849231,\"#D7E6F4\"],[0.163070599120654,\"#D6E5F4\"],[0.1648181386917,\"#D6E5F4\"],[0.164829658497982,\"#D6E5F4\"],[0.165251926083381,\"#D6E5F4\"],[0.165281214256075,\"#D6E5F4\"],[0.176074057695434,\"#D4E4F3\"],[0.177547109767516,\"#D4E4F3\"],[0.180215108968874,\"#D3E3F3\"],[0.181528926899385,\"#D3E3F3\"],[0.18200927177224,\"#D3E3F3\"],[0.184217142327857,\"#D2E3F3\"],[0.186836974506664,\"#D1E2F2\"],[0.186896495593756,\"#D1E2F2\"],[0.19477119473094,\"#D0E1F2\"],[0.196437751553831,\"#D0E1F2\"],[0.198958169425964,\"#CFE1F2\"],[0.199599204123416,\"#CFE1F2\"],[0.199643002704722,\"#CFE1F2\"],[0.205939628052291,\"#CEE0F1\"],[0.207338745441228,\"#CEE0F1\"],[0.207451038928221,\"#CEE0F1\"],[0.208286637250586,\"#CEE0F1\"],[0.213613705288465,\"#CDDFF1\"],[0.217633980358742,\"#CCDFF1\"],[0.219017992119371,\"#CBDEF0\"],[0.219238039033904,\"#CBDEF0\"],[0.219828980006303,\"#CBDEF0\"],[0.22051676674467,\"#CBDEF0\"],[0.220797228887767,\"#CBDEF0\"],[0.222253044854804,\"#CBDEF0\"],[0.229897462083034,\"#C9DDF0\"],[0.235277615529988,\"#C8DCEF\"],[0.23543567048956,\"#C8DCEF\"],[0.238387780704064,\"#C8DCEF\"],[0.245321426698747,\"#C6DBEF\"],[0.245824811756765,\"#C6DBEF\"],[0.248272216763125,\"#C6DBEF\"],[0.255258118966462,\"#C4DAEE\"],[0.25539117902522,\"#C4DAEE\"],[0.262948885760044,\"#C1D9ED\"],[0.271665869542777,\"#BFD8EC\"],[0.274683722730117,\"#BED7EC\"],[0.278454014117194,\"#BCD7EB\"],[0.280505026346822,\"#BBD6EB\"],[0.285460565623123,\"#BAD6EA\"],[0.287788284692333,\"#BAD6EA\"],[0.292778031055123,\"#B8D4EA\"],[0.295696949383387,\"#B7D4EA\"],[0.295734660011411,\"#B7D4EA\"],[0.301658910303963,\"#B5D3E9\"],[0.303006324046602,\"#B5D3E9\"],[0.303905626461184,\"#B5D3E9\"],[0.304817572789695,\"#B4D3E8\"],[0.307033923303471,\"#B3D3E8\"],[0.309844721395711,\"#B2D2E8\"],[0.310457200410047,\"#B2D2E8\"],[0.318011520183019,\"#B0D1E7\"],[0.318801655583425,\"#B0D1E7\"],[0.320846100415741,\"#AFD1E6\"],[0.321903369400093,\"#AFD1E6\"],[0.32244406175046,\"#AFD1E6\"],[0.325727661622098,\"#ADD0E6\"],[0.326463285635126,\"#ADD0E6\"],[0.330600515260223,\"#ACD0E6\"],[0.332852029421132,\"#ABCFE5\"],[0.334059480538155,\"#ABCFE5\"],[0.334570254727253,\"#ABCFE5\"],[0.336403906718691,\"#AACFE5\"],[0.338119112137043,\"#AACFE5\"],[0.341693315696117,\"#A8CEE4\"],[0.345093075355747,\"#A7CEE4\"],[0.348384569046878,\"#A6CDE3\"],[0.351129977629807,\"#A5CDE3\"],[0.357599483272661,\"#A3CCE3\"],[0.362172608061988,\"#A2CBE2\"],[0.363502861923713,\"#A1CBE2\"],[0.372116151704965,\"#9ECAE1\"],[0.373857483778625,\"#9ECAE1\"],[0.374968621142249,\"#9DC9E0\"],[0.377797614010294,\"#9CC9E0\"],[0.382049084643175,\"#9BC8E0\"],[0.384613999201764,\"#9AC7E0\"],[0.391551407290058,\"#97C6DF\"],[0.393413634291369,\"#96C6DF\"],[0.394726524387261,\"#96C5DF\"],[0.398016081357507,\"#94C5DF\"],[0.398090757930385,\"#94C4DE\"],[0.400725374496756,\"#93C4DE\"],[0.401015569024513,\"#93C4DE\"],[0.406501651460893,\"#91C2DE\"],[0.409738609943887,\"#90C2DE\"],[0.410008712407441,\"#8FC1DD\"],[0.411501854757207,\"#8FC1DD\"],[0.434988683676573,\"#85BCDB\"],[0.437590296823069,\"#84BBDB\"],[0.440755998903745,\"#83BBDB\"],[0.441880181094265,\"#82BADB\"],[0.445367826108455,\"#81B9DA\"],[0.448112949126574,\"#80B9DA\"],[0.450320578796944,\"#7FB8DA\"],[0.452636675796627,\"#7EB8DA\"],[0.454391396013767,\"#7DB8D9\"],[0.455760556744961,\"#7DB8D9\"],[0.462858065656792,\"#7AB6D9\"],[0.463214009841455,\"#7AB6D9\"],[0.463675071811737,\"#7AB6D9\"],[0.464204461437082,\"#79B6D9\"],[0.467734047728609,\"#78B5D8\"],[0.469637019864802,\"#77B4D8\"],[0.471174055309928,\"#77B4D8\"],[0.472437575771037,\"#76B4D8\"],[0.473621686944799,\"#75B3D8\"],[0.480273489712105,\"#73B2D7\"],[0.480784254803859,\"#72B1D7\"],[0.481303842133627,\"#72B1D7\"],[0.484807392774743,\"#71B1D7\"],[0.487021825059319,\"#70B1D7\"],[0.491472190827421,\"#6EB0D6\"],[0.49275331606036,\"#6EAFD6\"],[0.49414581896158,\"#6DAFD6\"],[0.495293243751349,\"#6CAFD6\"],[0.496659923518642,\"#6CAED6\"],[0.49811595358599,\"#6BAED6\"],[0.509561826896415,\"#67ABD4\"],[0.509783518401058,\"#67ABD4\"],[0.515216701198681,\"#66AAD4\"],[0.525729584351687,\"#62A8D2\"],[0.529033034945849,\"#61A7D2\"],[0.531763581261236,\"#60A6D1\"],[0.532717729177229,\"#60A6D1\"],[0.533096150331035,\"#60A6D1\"],[0.534163143993451,\"#60A6D1\"],[0.535580295292678,\"#5FA5D1\"],[0.536184545909484,\"#5FA5D1\"],[0.545980181296846,\"#5CA3D0\"],[0.550413307218695,\"#5AA3CF\"],[0.552259924114501,\"#59A2CF\"],[0.554582082266574,\"#59A2CF\"],[0.555883136314662,\"#58A1CE\"],[0.560359050607694,\"#57A0CE\"],[0.56572881621916,\"#559FCD\"],[0.572059422162612,\"#539DCC\"],[0.574129014267529,\"#529DCC\"],[0.577864390148239,\"#519CCC\"],[0.578557341817938,\"#509BCB\"],[0.585943534900779,\"#4F9BCB\"],[0.59451431070864,\"#4B98C9\"],[0.600934420551276,\"#4A97C9\"],[0.603028579702235,\"#4896C8\"],[0.603518277436298,\"#4896C8\"],[0.606803420347241,\"#4795C8\"],[0.611463125655814,\"#4694C7\"],[0.618872994218249,\"#4393C6\"],[0.622050632093838,\"#4292C6\"],[0.623942179795541,\"#4292C6\"],[0.638873044291007,\"#3E8EC4\"],[0.64202483918062,\"#3D8DC3\"],[0.645068858125427,\"#3D8DC3\"],[0.645581402670746,\"#3C8CC3\"],[0.646477338669936,\"#3C8CC3\"],[0.648475186589583,\"#3C8CC3\"],[0.65209843040106,\"#3B8BC2\"],[0.653022272989167,\"#3A8AC1\"],[0.653167734189465,\"#3A8AC1\"],[0.665568016626695,\"#3787C0\"],[0.667007964836916,\"#3787C0\"],[0.667785462581825,\"#3686C0\"],[0.682160053201915,\"#3282BE\"],[0.689156011292375,\"#3080BD\"],[0.705849662481414,\"#2C7CBB\"],[0.707463556363309,\"#2C7CBB\"],[0.708306581316802,\"#2B7BBA\"],[0.708316665856044,\"#2B7BBA\"],[0.718177853098515,\"#2979B9\"],[0.736263645750856,\"#2474B6\"],[0.73856184642803,\"#2474B6\"],[0.739869228579844,\"#2373B6\"],[0.742030952777324,\"#2373B6\"],[0.742781450226171,\"#2373B6\"],[0.765345298573847,\"#1E6DB2\"],[0.766915045456103,\"#1D6CB1\"],[0.777367942019409,\"#1B6AAF\"],[0.787178952652566,\"#1967AD\"],[0.789802194306684,\"#1967AD\"],[0.801230600000326,\"#1664AB\"],[0.815706630141315,\"#1360A7\"],[0.828481634580948,\"#115DA5\"],[0.855314778071882,\"#0C56A0\"],[0.857899290321775,\"#0B559F\"],[0.873978634377844,\"#08519C\"],[0.879882415822816,\"#08509A\"],[0.885602038677547,\"#084E97\"],[0.911879045679933,\"#08468D\"],[0.924414874434519,\"#084388\"],[0.932101354458042,\"#084185\"],[0.967808669559975,\"#083877\"],[0.973268306969539,\"#083775\"],[0.987566110737814,\"#08336F\"],[1,\"#08306B\"]],\"type\":\"heatmap\",\"showscale\":false,\"autocolorscale\":false,\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[1],\"name\":\"99_70f91f09e12c19553db815bf75656b6c\",\"type\":\"scatter\",\"mode\":\"markers\",\"opacity\":0,\"hoverinfo\":\"skip\",\"showlegend\":false,\"marker\":{\"color\":[0,1],\"colorscale\":[[0,\"#F7FBFF\"],[0.00334448160535117,\"#F6FAFE\"],[0.00668896321070234,\"#F5F9FE\"],[0.0100334448160535,\"#F4F9FE\"],[0.0133779264214047,\"#F4F9FE\"],[0.0167224080267559,\"#F3F8FD\"],[0.020066889632107,\"#F3F8FD\"],[0.0234113712374582,\"#F2F7FD\"],[0.0267558528428094,\"#F1F7FD\"],[0.0301003344481605,\"#F0F6FC\"],[0.0334448160535117,\"#EFF6FC\"],[0.0367892976588629,\"#EFF6FC\"],[0.040133779264214,\"#EFF5FC\"],[0.0434782608695652,\"#EEF5FC\"],[0.0468227424749164,\"#EDF4FB\"],[0.0501672240802676,\"#ECF4FB\"],[0.0535117056856187,\"#ECF3FB\"],[0.0568561872909699,\"#ECF3FB\"],[0.0602006688963211,\"#EBF3FB\"],[0.0635451505016722,\"#EAF2FA\"],[0.0668896321070234,\"#E9F2FA\"],[0.0702341137123746,\"#E8F1FA\"],[0.0735785953177257,\"#E8F1FA\"],[0.0769230769230769,\"#E7F0F9\"],[0.0802675585284281,\"#E7F0F9\"],[0.0836120401337793,\"#E6F0F9\"],[0.0869565217391304,\"#E5EFF9\"],[0.0903010033444816,\"#E4EFF9\"],[0.0936454849498328,\"#E4EEF8\"],[0.096989966555184,\"#E3EEF8\"],[0.100334448160535,\"#E2EDF8\"],[0.103678929765886,\"#E2EDF8\"],[0.107023411371237,\"#E1EDF8\"],[0.110367892976589,\"#E1ECF7\"],[0.11371237458194,\"#E0ECF7\"],[0.117056856187291,\"#DFEBF7\"],[0.120401337792642,\"#DEEBF7\"],[0.123745819397993,\"#DDEAF6\"],[0.127090301003344,\"#DDEAF6\"],[0.130434782608696,\"#DDEAF6\"],[0.133779264214047,\"#DCE9F6\"],[0.137123745819398,\"#DBE9F6\"],[0.140468227424749,\"#DAE8F5\"],[0.1438127090301,\"#DAE8F5\"],[0.147157190635451,\"#D9E7F5\"],[0.150501672240803,\"#D9E7F5\"],[0.153846153846154,\"#D8E7F5\"],[0.157190635451505,\"#D7E6F4\"],[0.160535117056856,\"#D7E6F4\"],[0.163879598662207,\"#D6E5F4\"],[0.167224080267559,\"#D5E5F4\"],[0.17056856187291,\"#D5E5F4\"],[0.173913043478261,\"#D4E4F3\"],[0.177257525083612,\"#D4E4F3\"],[0.180602006688963,\"#D3E3F3\"],[0.183946488294314,\"#D2E3F3\"],[0.187290969899666,\"#D1E2F2\"],[0.190635451505017,\"#D1E2F2\"],[0.193979933110368,\"#D1E2F2\"],[0.197324414715719,\"#D0E1F2\"],[0.20066889632107,\"#CFE1F2\"],[0.204013377926421,\"#CEE0F1\"],[0.207357859531773,\"#CEE0F1\"],[0.210702341137124,\"#CDDFF1\"],[0.214046822742475,\"#CCDFF1\"],[0.217391304347826,\"#CCDFF1\"],[0.220735785953177,\"#CBDEF0\"],[0.224080267558528,\"#CBDEF0\"],[0.22742474916388,\"#CADDF0\"],[0.230769230769231,\"#C9DDF0\"],[0.234113712374582,\"#C8DCEF\"],[0.237458193979933,\"#C8DCEF\"],[0.240802675585284,\"#C8DCEF\"],[0.244147157190635,\"#C7DBEF\"],[0.247491638795987,\"#C6DBEF\"],[0.250836120401338,\"#C5DAEE\"],[0.254180602006689,\"#C4DAEE\"],[0.25752508361204,\"#C3D9EE\"],[0.260869565217391,\"#C2D9ED\"],[0.264214046822742,\"#C1D9ED\"],[0.267558528428094,\"#C0D8ED\"],[0.270903010033445,\"#BFD8EC\"],[0.274247491638796,\"#BED7EC\"],[0.277591973244147,\"#BCD7EB\"],[0.280936454849498,\"#BBD6EB\"],[0.284280936454849,\"#BBD6EB\"],[0.287625418060201,\"#BAD6EA\"],[0.290969899665552,\"#B9D5EA\"],[0.294314381270903,\"#B7D4EA\"],[0.297658862876254,\"#B6D4E9\"],[0.301003344481605,\"#B5D3E9\"],[0.304347826086957,\"#B4D3E8\"],[0.307692307692308,\"#B3D3E8\"],[0.311036789297659,\"#B2D2E8\"],[0.31438127090301,\"#B1D2E7\"],[0.317725752508361,\"#B0D1E7\"],[0.321070234113712,\"#AFD1E6\"],[0.324414715719064,\"#AED0E6\"],[0.327759197324415,\"#ACD0E6\"],[0.331103678929766,\"#ACD0E6\"],[0.334448160535117,\"#ABCFE5\"],[0.337792642140468,\"#AACFE5\"],[0.341137123745819,\"#A8CEE4\"],[0.344481605351171,\"#A7CEE4\"],[0.347826086956522,\"#A6CDE3\"],[0.351170568561873,\"#A5CDE3\"],[0.354515050167224,\"#A4CDE3\"],[0.357859531772575,\"#A3CCE3\"],[0.361204013377926,\"#A2CBE2\"],[0.364548494983278,\"#A1CBE2\"],[0.367892976588629,\"#A0CAE1\"],[0.37123745819398,\"#9FCAE1\"],[0.374581939799331,\"#9DC9E0\"],[0.377926421404682,\"#9CC9E0\"],[0.381270903010033,\"#9BC8E0\"],[0.384615384615385,\"#9AC7E0\"],[0.387959866220736,\"#98C7DF\"],[0.391304347826087,\"#97C6DF\"],[0.394648829431438,\"#96C5DF\"],[0.397993311036789,\"#94C5DF\"],[0.40133779264214,\"#93C4DE\"],[0.404682274247492,\"#92C3DE\"],[0.408026755852843,\"#90C2DE\"],[0.411371237458194,\"#8FC1DD\"],[0.414715719063545,\"#8DC0DD\"],[0.418060200668896,\"#8CC0DD\"],[0.421404682274247,\"#8BC0DD\"],[0.424749163879599,\"#89BFDC\"],[0.42809364548495,\"#88BEDC\"],[0.431438127090301,\"#87BDDC\"],[0.434782608695652,\"#85BCDB\"],[0.438127090301003,\"#84BBDB\"],[0.441471571906354,\"#82BADB\"],[0.444816053511706,\"#81BADB\"],[0.448160535117057,\"#80B9DA\"],[0.451505016722408,\"#7FB8DA\"],[0.454849498327759,\"#7DB8D9\"],[0.45819397993311,\"#7BB7D9\"],[0.461538461538462,\"#7AB6D9\"],[0.464882943143813,\"#79B5D8\"],[0.468227424749164,\"#78B5D8\"],[0.471571906354515,\"#77B4D8\"],[0.474916387959866,\"#75B3D8\"],[0.478260869565217,\"#73B2D7\"],[0.481605351170569,\"#72B1D7\"],[0.48494983277592,\"#71B1D7\"],[0.488294314381271,\"#6FB0D6\"],[0.491638795986622,\"#6EB0D6\"],[0.494983277591973,\"#6DAFD6\"],[0.498327759197324,\"#6BAED6\"],[0.501672240802676,\"#6AADD5\"],[0.505016722408027,\"#69ACD5\"],[0.508361204013378,\"#68ABD4\"],[0.511705685618729,\"#67ABD4\"],[0.51505016722408,\"#66AAD4\"],[0.518394648829431,\"#65AAD3\"],[0.521739130434783,\"#63A9D3\"],[0.525083612040134,\"#62A8D2\"],[0.528428093645485,\"#61A7D2\"],[0.531772575250836,\"#60A6D1\"],[0.535117056856187,\"#5FA6D1\"],[0.538461538461538,\"#5EA5D1\"],[0.54180602006689,\"#5DA4D0\"],[0.545150501672241,\"#5CA3D0\"],[0.548494983277592,\"#5AA3CF\"],[0.551839464882943,\"#59A2CF\"],[0.555183946488294,\"#58A1CE\"],[0.558528428093645,\"#58A1CE\"],[0.561872909698997,\"#56A0CE\"],[0.565217391304348,\"#559FCD\"],[0.568561872909699,\"#549ECD\"],[0.57190635451505,\"#539DCC\"],[0.575250836120401,\"#529CCC\"],[0.578595317725752,\"#509BCB\"],[0.581939799331104,\"#509BCB\"],[0.585284280936455,\"#4F9BCB\"],[0.588628762541806,\"#4E9ACA\"],[0.591973244147157,\"#4C99CA\"],[0.595317725752508,\"#4B98C9\"],[0.598662207357859,\"#4A97C9\"],[0.602006688963211,\"#4996C8\"],[0.605351170568562,\"#4896C8\"],[0.608695652173913,\"#4795C8\"],[0.612040133779264,\"#4694C7\"],[0.615384615384615,\"#4594C7\"],[0.618729096989967,\"#4393C6\"],[0.622073578595318,\"#4292C6\"],[0.625418060200669,\"#4292C6\"],[0.62876254180602,\"#4191C5\"],[0.632107023411371,\"#4090C5\"],[0.635451505016722,\"#3F8FC4\"],[0.638795986622074,\"#3E8EC4\"],[0.642140468227425,\"#3D8DC3\"],[0.645484949832776,\"#3C8CC3\"],[0.648829431438127,\"#3C8CC3\"],[0.652173913043478,\"#3B8BC2\"],[0.655518394648829,\"#3A8AC1\"],[0.658862876254181,\"#3989C1\"],[0.662207357859532,\"#3888C0\"],[0.665551839464883,\"#3787C0\"],[0.668896321070234,\"#3686BF\"],[0.672240802675585,\"#3585BF\"],[0.675585284280936,\"#3484BF\"],[0.678929765886288,\"#3383BE\"],[0.682274247491639,\"#3282BE\"],[0.68561872909699,\"#3181BD\"],[0.688963210702341,\"#3080BD\"],[0.692307692307692,\"#2F7FBC\"],[0.695652173913043,\"#2F7FBC\"],[0.698996655518395,\"#2E7EBC\"],[0.702341137123746,\"#2D7DBB\"],[0.705685618729097,\"#2C7CBB\"],[0.709030100334448,\"#2B7BBA\"],[0.712374581939799,\"#2A7AB9\"],[0.71571906354515,\"#2979B9\"],[0.719063545150502,\"#2979B9\"],[0.722408026755853,\"#2878B8\"],[0.725752508361204,\"#2777B8\"],[0.729096989966555,\"#2676B7\"],[0.732441471571906,\"#2575B7\"],[0.735785953177257,\"#2474B6\"],[0.739130434782609,\"#2474B6\"],[0.74247491638796,\"#2373B6\"],[0.745819397993311,\"#2272B5\"],[0.749163879598662,\"#2171B5\"],[0.752508361204013,\"#2070B4\"],[0.755852842809364,\"#1F6FB3\"],[0.759197324414716,\"#1E6EB2\"],[0.762541806020067,\"#1E6EB2\"],[0.765886287625418,\"#1E6DB2\"],[0.769230769230769,\"#1D6CB1\"],[0.77257525083612,\"#1C6BB0\"],[0.775919732441472,\"#1B6AAF\"],[0.779264214046823,\"#1A69AE\"],[0.782608695652174,\"#1A68AE\"],[0.785953177257525,\"#1A68AE\"],[0.789297658862876,\"#1967AD\"],[0.792642140468227,\"#1866AC\"],[0.795986622073579,\"#1765AB\"],[0.79933110367893,\"#1664AB\"],[0.802675585284281,\"#1663AA\"],[0.806020066889632,\"#1562A9\"],[0.809364548494983,\"#1562A9\"],[0.812709030100334,\"#1461A8\"],[0.816053511705686,\"#1360A7\"],[0.819397993311037,\"#135FA7\"],[0.822742474916388,\"#125EA6\"],[0.826086956521739,\"#115DA5\"],[0.82943143812709,\"#105CA4\"],[0.832775919732441,\"#105CA4\"],[0.836120401337793,\"#0F5BA3\"],[0.839464882943144,\"#0F5AA3\"],[0.842809364548495,\"#0E59A2\"],[0.846153846153846,\"#0D58A1\"],[0.849498327759197,\"#0C57A0\"],[0.852842809364548,\"#0C57A0\"],[0.8561872909699,\"#0C56A0\"],[0.859531772575251,\"#0B559F\"],[0.862876254180602,\"#0A549E\"],[0.866220735785953,\"#09539D\"],[0.869565217391304,\"#08529C\"],[0.872909698996655,\"#08519C\"],[0.876254180602007,\"#08519B\"],[0.879598662207358,\"#08509A\"],[0.882943143812709,\"#084F99\"],[0.88628762541806,\"#084E97\"],[0.889632107023411,\"#084C96\"],[0.892976588628763,\"#084B95\"],[0.896321070234114,\"#084A93\"],[0.899665551839465,\"#084A92\"],[0.903010033444816,\"#084990\"],[0.906354515050167,\"#08488F\"],[0.909698996655518,\"#08478E\"],[0.91304347826087,\"#08468C\"],[0.916387959866221,\"#08458B\"],[0.919732441471572,\"#08448A\"],[0.923076923076923,\"#084489\"],[0.926421404682274,\"#084388\"],[0.929765886287625,\"#084286\"],[0.933110367892977,\"#084185\"],[0.936454849498328,\"#084083\"],[0.939799331103679,\"#083F82\"],[0.94314381270903,\"#083E81\"],[0.946488294314381,\"#083E7F\"],[0.949832775919732,\"#083D7E\"],[0.953177257525084,\"#083C7D\"],[0.956521739130435,\"#083B7B\"],[0.959866220735786,\"#083A7A\"],[0.963210702341137,\"#083979\"],[0.966555183946488,\"#083978\"],[0.969899665551839,\"#083876\"],[0.973244147157191,\"#083775\"],[0.976588628762542,\"#083674\"],[0.979933110367893,\"#083572\"],[0.983277591973244,\"#083471\"],[0.986622073578595,\"#083370\"],[0.989966555183946,\"#08336F\"],[0.993311036789298,\"#08326D\"],[0.996655518394649,\"#08316C\"],[1,\"#08306B\"]],\"colorbar\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"thickness\":23.04,\"title\":null,\"titlefont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"tickmode\":\"array\",\"ticktext\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"ticklen\":2,\"len\":0.5}},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.09087788975901,1.09087788975901,null,1.09087788975901,0.500949721963311,null,0.500949721963311,0.500949721963311,null,0.500949721963311,0,null,0.500949721963311,0.500949721963311,null,0.500949721963311,0],\"y\":[45.609375,42.5,null,42.5,42.5,null,42.5,42,null,42,42,null,42.5,43,null,43,43],\"text\":[\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(57,190,177,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#39BEB1,solid)\",\"legendgroup\":\"(#39BEB1,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.09087788975901,1.09087788975901,null,1.09087788975901,0.731800222126064,null,0.731800222126064,0.731800222126064,null,0.731800222126064,0.691159533269081,null,0.691159533269081,0.691159533269081,null,0.691159533269081,0.380627098188748,null,0.380627098188748,0.380627098188748,null,0.380627098188748,0.255264316891836,null,0.255264316891836,0.255264316891836,null,0.255264316891836,0,null,0.255264316891836,0.255264316891836,null,0.255264316891836,0.185675404080306,null,0.185675404080306,0.185675404080306,null,0.185675404080306,0,null,0.185675404080306,0.185675404080306,null,0.185675404080306,0,null,0.380627098188748,0.380627098188748,null,0.380627098188748,0,null,0.691159533269081,0.691159533269081,null,0.691159533269081,0,null,0.731800222126064,0.731800222126064,null,0.731800222126064,0.466807582689693,null,0.466807582689693,0.466807582689693,null,0.466807582689693,0.358417482296682,null,0.358417482296682,0.358417482296682,null,0.358417482296682,0,null,0.358417482296682,0.358417482296682,null,0.358417482296682,0,null,0.466807582689693,0.466807582689693,null,0.466807582689693,0.173019976310583,null,0.173019976310583,0.173019976310583,null,0.173019976310583,0,null,0.173019976310583,0.173019976310583,null,0.173019976310583,0],\"y\":[45.609375,48.71875,null,48.71875,48.71875,null,48.71875,46.9375,null,46.9375,46.9375,null,46.9375,45.875,null,45.875,45.875,null,45.875,44.75,null,44.75,44.75,null,44.75,44,null,44,44,null,44.75,45.5,null,45.5,45.5,null,45.5,45,null,45,45,null,45.5,46,null,46,46,null,45.875,47,null,47,47,null,46.9375,48,null,48,48,null,48.71875,50.5,null,50.5,50.5,null,50.5,49.5,null,49.5,49.5,null,49.5,49,null,49,49,null,49.5,50,null,50,50,null,50.5,51.5,null,51.5,51.5,null,51.5,51,null,51,51,null,51.5,52,null,52,52],\"text\":[\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(125,176,221,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#7DB0DD,solid)\",\"legendgroup\":\"(#7DB0DD,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.05439722722438,1.05439722722438,null,1.05439722722438,0.47350573521867,null,0.47350573521867,0.47350573521867,null,0.47350573521867,0,null,0.47350573521867,0.47350573521867,null,0.47350573521867,0],\"y\":[37.859375,40.5,null,40.5,40.5,null,40.5,40,null,40,40,null,40.5,41,null,41,41],\"text\":[\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(134,184,117,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#86B875,solid)\",\"legendgroup\":\"(#86B875,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.05439722722438,1.05439722722438,null,1.05439722722438,0.659367031899142,null,0.659367031899142,0.659367031899142,null,0.659367031899142,0,null,0.659367031899142,0.659367031899142,null,0.659367031899142,0.366446818172613,null,0.366446818172613,0.366446818172613,null,0.366446818172613,0,null,0.366446818172613,0.366446818172613,null,0.366446818172613,0.257294381800551,null,0.257294381800551,0.257294381800551,null,0.257294381800551,0.202445065633869,null,0.202445065633869,0.202445065633869,null,0.202445065633869,0,null,0.202445065633869,0.202445065633869,null,0.202445065633869,0.128883042294223,null,0.128883042294223,0.128883042294223,null,0.128883042294223,0,null,0.128883042294223,0.128883042294223,null,0.128883042294223,0,null,0.257294381800551,0.257294381800551,null,0.257294381800551,0],\"y\":[37.859375,35.21875,null,35.21875,35.21875,null,35.21875,34,null,34,34,null,35.21875,36.4375,null,36.4375,36.4375,null,36.4375,35,null,35,35,null,36.4375,37.875,null,37.875,37.875,null,37.875,36.75,null,36.75,36.75,null,36.75,36,null,36,36,null,36.75,37.5,null,37.5,37.5,null,37.5,37,null,37,37,null,37.5,38,null,38,38,null,37.875,39,null,39,39],\"text\":[\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.25729438\",\"y: 0.25729438\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(199,167,108,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#C7A76C,solid)\",\"legendgroup\":\"(#C7A76C,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.59417446669873,1.59417446669873,null,1.59417446669873,0.614248456260233,null,0.614248456260233,0.614248456260233,null,0.614248456260233,0.275857868808986,null,0.275857868808986,0.275857868808986,null,0.275857868808986,0,null,0.275857868808986,0.275857868808986,null,0.275857868808986,0,null,0.614248456260233,0.614248456260233,null,0.614248456260233,0],\"y\":[49.9296875,54.25,null,54.25,54.25,null,54.25,53.5,null,53.5,53.5,null,53.5,53,null,53,53,null,53.5,54,null,54,54,null,54.25,55,null,55,55],\"text\":[\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.61424846\",\"y: 0.61424846\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(205,153,216,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#CD99D8,solid)\",\"legendgroup\":\"(#CD99D8,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.20466483415084,1.20466483415084,null,1.20466483415084,0.95788286362071,null,0.95788286362071,0.95788286362071,null,0.95788286362071,0.794745500284792,null,0.794745500284792,0.794745500284792,null,0.794745500284792,0.381625693962732,null,0.381625693962732,0.381625693962732,null,0.381625693962732,0,null,0.381625693962732,0.381625693962732,null,0.381625693962732,0,null,0.794745500284792,0.794745500284792,null,0.794745500284792,0.666404776934707,null,0.666404776934707,0.666404776934707,null,0.666404776934707,0.367061621439879,null,0.367061621439879,0.367061621439879,null,0.367061621439879,0,null,0.367061621439879,0.367061621439879,null,0.367061621439879,0.248285826616636,null,0.248285826616636,0.248285826616636,null,0.248285826616636,0.0875581071177939,null,0.0875581071177939,0.0875581071177939,null,0.0875581071177939,0,null,0.0875581071177939,0.0875581071177939,null,0.0875581071177939,0,null,0.248285826616636,0.248285826616636,null,0.248285826616636,0.237569649714429,null,0.237569649714429,0.237569649714429,null,0.237569649714429,0.129904663635189,null,0.129904663635189,0.129904663635189,null,0.129904663635189,0,null,0.129904663635189,0.129904663635189,null,0.129904663635189,0,null,0.237569649714429,0.237569649714429,null,0.237569649714429,0,null,0.666404776934707,0.666404776934707,null,0.666404776934707,0.534875118690448,null,0.534875118690448,0.534875118690448,null,0.534875118690448,0.438363599370831,null,0.438363599370831,0.438363599370831,null,0.438363599370831,0.20347407832471,null,0.20347407832471,0.20347407832471,null,0.20347407832471,0,null,0.20347407832471,0.20347407832471,null,0.20347407832471,0,null,0.438363599370831,0.438363599370831,null,0.438363599370831,0.332059186086582,null,0.332059186086582,0.332059186086582,null,0.332059186086582,0.274199290988404,null,0.274199290988404,0.274199290988404,null,0.274199290988404,0,null,0.274199290988404,0.274199290988404,null,0.274199290988404,0.143438256757787,null,0.143438256757787,0.143438256757787,null,0.143438256757787,0,null,0.143438256757787,0.143438256757787,null,0.143438256757787,0,null,0.332059186086582,0.332059186086582,null,0.332059186086582,0.20894513119211,null,0.20894513119211,0.20894513119211,null,0.20894513119211,0,null,0.20894513119211,0.20894513119211,null,0.20894513119211,0.154458411843452,null,0.154458411843452,0.154458411843452,null,0.154458411843452,0.0903999281103318,null,0.0903999281103318,0.0903999281103318,null,0.0903999281103318,0,null,0.0903999281103318,0.0903999281103318,null,0.0903999281103318,0,null,0.154458411843452,0.154458411843452,null,0.154458411843452,0,null,0.534875118690448,0.534875118690448,null,0.534875118690448,0.372123275507687,null,0.372123275507687,0.372123275507687,null,0.372123275507687,0.35032421362806,null,0.35032421362806,0.35032421362806,null,0.35032421362806,0.243402838861005,null,0.243402838861005,0.243402838861005,null,0.243402838861005,0.212443162483461,null,0.212443162483461,0.212443162483461,null,0.212443162483461,0.127081711167596,null,0.127081711167596,0.127081711167596,null,0.127081711167596,0,null,0.127081711167596,0.127081711167596,null,0.127081711167596,0,null,0.212443162483461,0.212443162483461,null,0.212443162483461,0,null,0.243402838861005,0.243402838861005,null,0.243402838861005,0,null,0.35032421362806,0.35032421362806,null,0.35032421362806,0,null,0.372123275507687,0.372123275507687,null,0.372123275507687,0.182577335771184,null,0.182577335771184,0.182577335771184,null,0.182577335771184,0,null,0.182577335771184,0.182577335771184,null,0.182577335771184,0.121298312556643,null,0.121298312556643,0.121298312556643,null,0.121298312556643,0,null,0.121298312556643,0.121298312556643,null,0.121298312556643,0.0949020854651998,null,0.0949020854651998,0.0949020854651998,null,0.0949020854651998,0,null,0.0949020854651998,0.0949020854651998,null,0.0949020854651998,0,null,0.95788286362071,0.95788286362071,null,0.95788286362071,0.407830626686954,null,0.407830626686954,0.407830626686954,null,0.407830626686954,0.218154484501404,null,0.218154484501404,0.218154484501404,null,0.218154484501404,0.0991867532043192,null,0.0991867532043192,0.0991867532043192,null,0.0991867532043192,0,null,0.0991867532043192,0.0991867532043192,null,0.0991867532043192,0,null,0.218154484501404,0.218154484501404,null,0.218154484501404,0,null,0.407830626686954,0.407830626686954,null,0.407830626686954,0.319599624724541,null,0.319599624724541,0.319599624724541,null,0.319599624724541,0.209182472124278,null,0.209182472124278,0.209182472124278,null,0.209182472124278,0,null,0.209182472124278,0.209182472124278,null,0.209182472124278,0,null,0.319599624724541,0.319599624724541,null,0.319599624724541,0.119504801735496,null,0.119504801735496,0.119504801735496,null,0.119504801735496,0,null,0.119504801735496,0.119504801735496,null,0.119504801735496,0],\"y\":[27.923828125,17.98828125,null,17.98828125,17.98828125,null,17.98828125,6.1015625,null,6.1015625,6.1015625,null,6.1015625,1.5,null,1.5,1.5,null,1.5,1,null,1,1,null,1.5,2,null,2,2,null,6.1015625,10.703125,null,10.703125,10.703125,null,10.703125,4.4375,null,4.4375,4.4375,null,4.4375,3,null,3,3,null,4.4375,5.875,null,5.875,5.875,null,5.875,4.5,null,4.5,4.5,null,4.5,4,null,4,4,null,4.5,5,null,5,5,null,5.875,7.25,null,7.25,7.25,null,7.25,6.5,null,6.5,6.5,null,6.5,6,null,6,6,null,6.5,7,null,7,7,null,7.25,8,null,8,8,null,10.703125,16.96875,null,16.96875,16.96875,null,16.96875,11.46875,null,11.46875,11.46875,null,11.46875,9.5,null,9.5,9.5,null,9.5,9,null,9,9,null,9.5,10,null,10,10,null,11.46875,13.4375,null,13.4375,13.4375,null,13.4375,11.75,null,11.75,11.75,null,11.75,11,null,11,11,null,11.75,12.5,null,12.5,12.5,null,12.5,12,null,12,12,null,12.5,13,null,13,13,null,13.4375,15.125,null,15.125,15.125,null,15.125,14,null,14,14,null,15.125,16.25,null,16.25,16.25,null,16.25,15.5,null,15.5,15.5,null,15.5,15,null,15,15,null,15.5,16,null,16,16,null,16.25,17,null,17,17,null,16.96875,22.46875,null,22.46875,22.46875,null,22.46875,21.0625,null,21.0625,21.0625,null,21.0625,20.125,null,20.125,20.125,null,20.125,19.25,null,19.25,19.25,null,19.25,18.5,null,18.5,18.5,null,18.5,18,null,18,18,null,18.5,19,null,19,19,null,19.25,20,null,20,20,null,20.125,21,null,21,21,null,21.0625,22,null,22,22,null,22.46875,23.875,null,23.875,23.875,null,23.875,23,null,23,23,null,23.875,24.75,null,24.75,24.75,null,24.75,24,null,24,24,null,24.75,25.5,null,25.5,25.5,null,25.5,25,null,25,25,null,25.5,26,null,26,26,null,17.98828125,29.875,null,29.875,29.875,null,29.875,28.25,null,28.25,28.25,null,28.25,27.5,null,27.5,27.5,null,27.5,27,null,27,27,null,27.5,28,null,28,28,null,28.25,29,null,29,29,null,29.875,31.5,null,31.5,31.5,null,31.5,30.5,null,30.5,30.5,null,30.5,30,null,30,30,null,30.5,31,null,31,31,null,31.5,32.5,null,32.5,32.5,null,32.5,32,null,32,32,null,32.5,33,null,33,33],\"text\":[\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(228,149,165,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(#E495A5,solid)\",\"legendgroup\":\"(#E495A5,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.82287715348419,1.82287715348419,null,1.82287715348419,1.20466483415084,null,1.20466483415084,1.20466483415084,null,1.20466483415084,1.05439722722438,null,1.82287715348419,1.82287715348419,null,1.82287715348419,1.59417446669873,null,1.59417446669873,1.59417446669873,null,1.59417446669873,1.09087788975901],\"y\":[38.9267578125,27.923828125,null,27.923828125,27.923828125,null,27.923828125,37.859375,null,37.859375,37.859375,null,38.9267578125,49.9296875,null,49.9296875,49.9296875,null,49.9296875,45.609375,null,45.609375,45.609375],\"text\":[\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 1.59417447\",\"y: 1.59417447\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.26771653543307,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"(black,solid)\",\"legendgroup\":\"(black,solid)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.82287715348419,1.20466483415084,0.95788286362071,0.794745500284792,0.381625693962732,0,0,0.666404776934707,0.367061621439879,0,0.248285826616636,0.0875581071177939,0,0,0.237569649714429,0.129904663635189,0,0,0,0.534875118690448,0.438363599370831,0.20347407832471,0,0,0.332059186086582,0.274199290988404,0,0.143438256757787,0,0,0.20894513119211,0,0.154458411843452,0.0903999281103318,0,0,0,0.372123275507687,0.35032421362806,0.243402838861005,0.212443162483461,0.127081711167596,0,0,0,0,0,0.182577335771184,0,0.121298312556643,0,0.0949020854651998,0,0,0.407830626686954,0.218154484501404,0.0991867532043192,0,0,0,0.319599624724541,0.209182472124278,0,0,0.119504801735496,0,0,1.05439722722438,0.659367031899142,0,0.366446818172613,0,0.257294381800551,0.202445065633869,0,0.128883042294223,0,0,0,0.47350573521867,0,0,1.59417446669873,1.09087788975901,0.500949721963311,0,0,0.731800222126064,0.691159533269081,0.380627098188748,0.255264316891836,0,0.185675404080306,0,0,0,0,0.466807582689693,0.358417482296682,0,0,0.173019976310583,0,0,0.614248456260233,0.275857868808986,0,0,0],\"y\":[38.9267578125,27.923828125,17.98828125,6.1015625,1.5,1,2,10.703125,4.4375,3,5.875,4.5,4,5,7.25,6.5,6,7,8,16.96875,11.46875,9.5,9,10,13.4375,11.75,11,12.5,12,13,15.125,14,16.25,15.5,15,16,17,22.46875,21.0625,20.125,19.25,18.5,18,19,20,21,22,23.875,23,24.75,24,25.5,25,26,29.875,28.25,27.5,27,28,29,31.5,30.5,30,31,32.5,32,33,37.859375,35.21875,34,36.4375,35,37.875,36.75,36,37.5,37,38,39,40.5,40,41,49.9296875,45.609375,42.5,42,43,48.71875,46.9375,45.875,44.75,44,45.5,45,46,47,48,50.5,49.5,49,50,51.5,51,52,54.25,53.5,53,54,55],\"text\":[\"y: 1.82287715\",\"y: 1.20466483\",\"y: 0.95788286\",\"y: 0.79474550\",\"y: 0.38162569\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.66640478\",\"y: 0.36706162\",\"y: 0.00000000\",\"y: 0.24828583\",\"y: 0.08755811\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.23756965\",\"y: 0.12990466\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.53487512\",\"y: 0.43836360\",\"y: 0.20347408\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.33205919\",\"y: 0.27419929\",\"y: 0.00000000\",\"y: 0.14343826\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.20894513\",\"y: 0.00000000\",\"y: 0.15445841\",\"y: 0.09039993\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.37212328\",\"y: 0.35032421\",\"y: 0.24340284\",\"y: 0.21244316\",\"y: 0.12708171\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.18257734\",\"y: 0.00000000\",\"y: 0.12129831\",\"y: 0.00000000\",\"y: 0.09490209\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.40783063\",\"y: 0.21815448\",\"y: 0.09918675\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.31959962\",\"y: 0.20918247\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.11950480\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 1.05439723\",\"y: 0.65936703\",\"y: 0.00000000\",\"y: 0.36644682\",\"y: 0.00000000\",\"y: 0.25729438\",\"y: 0.20244507\",\"y: 0.00000000\",\"y: 0.12888304\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.47350574\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 1.59417447\",\"y: 1.09087789\",\"y: 0.50094972\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.73180022\",\"y: 0.69115953\",\"y: 0.38062710\",\"y: 0.25526432\",\"y: 0.00000000\",\"y: 0.18567540\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.46680758\",\"y: 0.35841748\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.17301998\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.61424846\",\"y: 0.27585787\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"transparent\",\"opacity\":1,\"size\":null,\"symbol\":null,\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"hoveron\":\"points\",\"name\":\"(NA,1)\",\"legendgroup\":\"(NA,1)\",\"showlegend\":true,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"xaxis\":{\"domain\":[0,0.8],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.5,5.5],\"tickmode\":\"array\",\"ticktext\":[\"RADIO_PR\",\"TV_PR\",\"LLPHONE_PR\",\"MPHONE_PR\",\"COMPUTER_PR\"],\"tickvals\":[1,2,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"RADIO_PR\",\"TV_PR\",\"LLPHONE_PR\",\"MPHONE_PR\",\"COMPUTER_PR\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":6.6417600664176},\"tickangle\":-45,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"ICT Indicators\",\"hoverformat\":\".2f\"},\"xaxis2\":{\"domain\":[0.8,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0,1.82287715348419],\"tickmode\":\"array\",\"ticktext\":[\"0.0\",\"0.5\",\"1.0\",\"1.5\"],\"tickvals\":[0,0.5,1,1.5],\"categoryorder\":\"array\",\"categoryarray\":[\"0.0\",\"0.5\",\"1.0\",\"1.5\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.65296803652968,\"tickwidth\":0,\"showticklabels\":false,\"tickfont\":{\"color\":null,\"family\":null,\"size\":0},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"\",\"font\":{\"color\":null,\"family\":null,\"size\":0}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.5,55.5],\"tickmode\":\"array\",\"ticktext\":[\"Narphan\",\"Pangwaun\",\"Mongpan\",\"Nansang\",\"Kyaukme\",\"Kalaw\",\"Hseni\",\"Langkho\",\"Kunhing\",\"Laihka\",\"Monghsat\",\"Loilen\",\"Mongnai\",\"Mongton\",\"Hsipaw\",\"Hopong\",\"Monghsu\",\"Pinlaung\",\"Mongmit\",\"Pekon\",\"Kutkai\",\"Namtu\",\"Hsihseng\",\"Kyethi\",\"Tangyan\",\"Namhsan\",\"Mongyai\",\"Mongping\",\"Mongkhet\",\"Mawkmai\",\"Mongkaing\",\"Manton\",\"Matman\",\"Ywangan\",\"Pindaya\",\"Lawksawk\",\"Nyaungshwe\",\"Nawnghkio\",\"Monghpyak\",\"Mabein\",\"Mongyawng\",\"Kunlong\",\"Konkyan\",\"Mongyang\",\"Mongmao\",\"Hopang\",\"Namhkan\",\"Laukkaing\",\"Mongla\",\"Pangsang\",\"Kengtung\",\"Lashio\",\"Taunggyi\",\"Tachileik\",\"Muse\"],\"tickvals\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55],\"categoryorder\":\"array\",\"categoryarray\":[\"Narphan\",\"Pangwaun\",\"Mongpan\",\"Nansang\",\"Kyaukme\",\"Kalaw\",\"Hseni\",\"Langkho\",\"Kunhing\",\"Laihka\",\"Monghsat\",\"Loilen\",\"Mongnai\",\"Mongton\",\"Hsipaw\",\"Hopong\",\"Monghsu\",\"Pinlaung\",\"Mongmit\",\"Pekon\",\"Kutkai\",\"Namtu\",\"Hsihseng\",\"Kyethi\",\"Tangyan\",\"Namhsan\",\"Mongyai\",\"Mongping\",\"Mongkhet\",\"Mawkmai\",\"Mongkaing\",\"Manton\",\"Matman\",\"Ywangan\",\"Pindaya\",\"Lawksawk\",\"Nyaungshwe\",\"Nawnghkio\",\"Monghpyak\",\"Mabein\",\"Mongyawng\",\"Kunlong\",\"Konkyan\",\"Mongyang\",\"Mongmao\",\"Hopang\",\"Namhkan\",\"Laukkaing\",\"Mongla\",\"Pangsang\",\"Kengtung\",\"Lashio\",\"Taunggyi\",\"Tachileik\",\"Muse\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":5.31340805313408},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"Townships of Shan State\",\"hoverformat\":\".2f\"},\"annotations\":[],\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.8,\"y0\":0,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.8,\"x1\":1,\"y0\":0,\"y1\":1}],\"images\":[],\"margin\":{\"t\":60,\"r\":null,\"b\":35.0684931506849,\"l\":200},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"y\":1,\"yanchor\":\"top\"},\"hovermode\":\"closest\",\"barmode\":\"relative\",\"title\":\"Geographic Segmentation of Shan State by ICT indicators\"},\"attrs\":{\"66d84d6872ac\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"heatmap\"},\"66d864da74b4\":{\"xend\":{},\"yend\":{},\"colour\":{},\"linetype\":{},\"size\":{},\"x\":{},\"y\":{},\"type\":\"scatter\"},\"66d81ed23b47\":{\"colour\":{},\"shape\":{},\"size\":{},\"x\":{},\"y\":{}}},\"source\":\"A\",\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displaylogo\":false,\"modeBarButtonsToRemove\":[\"sendDataToCloud\",\"select2d\",\"lasso2d\",\"autoScale2d\",\"hoverClosestCartesian\",\"hoverCompareCartesian\",\"sendDataToCloud\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"subplot\":true,\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n### 7.14. Mapping the clusters formed\n\nWith closed examination of the dendragram above, we have decided to retain six clusters.\n\n[*cutree()*](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cutree.html) of **Base R** will be used in the code chunk below to derive a 6-cluster model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups <- as.factor(cutree(hclust_ward, k=6))\n```\n:::\n\n\nThe output is called `groups`. It is a **list** object.\n\nIn order to visualise the clusters, the *groups* object need to be appended onto `shan_sf` simple feature object.\n\nThe code chunk below form the join in three steps:\n\n-   the `groups` list object will be converted into a matrix;\n\n-   *cbind()* is used to append `groups` matrix onto `shan_sf` to produce an output simple feature object called `shan_sf_cluster`; and\n\n-   *rename()* of **dplyr** package is used to rename `as.matrix.groups` field as `CLUSTER`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_cluster <- cbind(shan_sf, as.matrix(groups)) %>%\n  rename(`CLUSTER`=`as.matrix.groups.`)\n```\n:::\n\n\nNext, *qtm()* of **tmap** package is used to plot the choropleth map showing the cluster formed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqtm(shan_sf_cluster, \"CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nThe choropleth map above reveals the clusters are very fragmented. The is one of the major limitation when non-spatial clustering algorithm such as hierarchical cluster analysis method is used.\n\n## 8. Spatially Constrained Clustering - SKATER Approach\n\nIn this section, we will derive spatially constrained cluster by using [*skater()*](https://r-spatial.github.io/spdep/reference/skater.html) method of [**spdep**](https://r-spatial.github.io/spdep/) package.\n\n### 8.1. Converting Simple Features Data.frame into SpatialPolygonsDataFrame\n\nFirst, we need to convert `shan_sf` into SpatialPolygonsDataFrame. This is because SKATER function only support **sp** objects such as SpatialPolygonDataFrame.\n\nThe code chunk below uses [*as_Spatial()*](https://r-spatial.github.io/sf/reference/coerce-methods.html) of **sf** package to convert *shan_sf* into a SpatialPolygonDataFrame called *shan_sp*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sp <- as_Spatial(shan_sf)\n```\n:::\n\n\n### 8.2. Computing Neighbour List\n\nNext, [*poly2nd()*](https://r-spatial.github.io/spdep/reference/poly2nb.html) of **spdep** package will be used to compute the neighbours list from polygon list. In the code chunk below, the default Queen's contiguity method is used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan.nb <- poly2nb(shan_sp)\nsummary(shan.nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNeighbour list object:\nNumber of regions: 55 \nNumber of nonzero links: 264 \nPercentage nonzero weights: 8.727273 \nAverage number of links: 4.8 \nLink number distribution:\n\n 2  3  4  5  6  7  8  9 \n 5  9  7 21  4  3  5  1 \n5 least connected regions:\n3 5 7 9 47 with 2 links\n1 most connected region:\n8 with 9 links\n```\n:::\n:::\n\n\nThere are 264 pairs of neighbours defined based on the definition of at least 1 shared boundary point, among the 55 towns in Shan State.\n\nWe can plot the neighbours list on `shan_sp` by using the code chunk below. Since we now can plot the community area boundaries as well, we plot this graph on top of the map. The first plot command gives the boundaries. This is followed by the plot of the neighbor list object, with coordinates applied to the original SpatialPolygonDataFrame (Shan State township boundaries) to extract the centroids of the polygons. These are used as the nodes for the graph representation. We also set the color to blue and specify `add=TRUE` to plot the network on top of the boundaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(shan_sp, \n     border=grey(.5))\nplot(shan.nb, \n     coordinates(shan_sp), \n     col=\"blue\", \n     add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nNote that when plotting the network first and then the boundaries, some of the areas will be clipped. This is because the plotting area is determined by the characteristics of the first plot. In this example, because the boundary map extends further than the graph, we plot it first.\n\n### 8.3. Computing Edge Costs\n\nNext, [*nbcosts()*](https://r-spatial.github.io/spdep/reference/nbcosts.html) of **spdep** package is used to compute the cost of each edge. It is the distance between it nodes. This function compute this distance using a data.frame with observations vector in each node.\n\nThe code chunk below is used to compute the cost of each edge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcosts <- nbcosts(shan.nb, shan_ict)\n```\n:::\n\n\nFor each observation, this gives the pairwise dissimilarity between its values on the five variables and the values for the neighbouring observation (from the neighbour list). Basically, this is the notion of a generalised weight for a spatial weights matrix.\n\nNext, We will incorporate these costs into a weights object in the same way as we did in the calculation of inverse of distance weights. In other words, we convert the neighbour list to a list weights object by specifying the just computed `lcosts` as the weights.\n\nIn order to achieve this, [*nb2listw()*](https://r-spatial.github.io/spdep/reference/nb2listw.html) of **spdep** package is used as shown in the code chunk below.\n\nNote that we specify the `style=\"B\"` to make sure the cost values are [not]{.underline} row-standardised.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan.w <- nb2listw(shan.nb, \n                   lcosts, \n                   style=\"B\")\nsummary(shan.w)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 55 \nNumber of nonzero links: 264 \nPercentage nonzero weights: 8.727273 \nAverage number of links: 4.8 \nLink number distribution:\n\n 2  3  4  5  6  7  8  9 \n 5  9  7 21  4  3  5  1 \n5 least connected regions:\n3 5 7 9 47 with 2 links\n1 most connected region:\n8 with 9 links\n\nWeights style: B \nWeights constants summary:\n   n   nn       S0       S1        S2\nB 55 3025 76267.65 58260785 522016004\n```\n:::\n:::\n\n\n### 8.4. Computing Minimum Spanning Tree\n\nThe minimum spanning tree is computed by mean of the [*mstree()*](https://r-spatial.github.io/spdep/reference/mstree.html) of **spdep** package as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan.mst <- mstree(shan.w)\n```\n:::\n\n\nAfter computing the MST, we can check its class and dimension by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"mst\"    \"matrix\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 54  3\n```\n:::\n:::\n\n\nR tells us that it is a 54 by 3 matrix. The dimension is 1 less than the total number of towns of 55 in Shan State, because the minimum spanning tree consists on n-1 edges (links) in order to traverse all the nodes.\n\nWe can display the content of *shan.mst* by using *head()* as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2]      [,3]\n[1,]   31   25 229.44658\n[2,]   25   10 163.95741\n[3,]   10    1 144.02475\n[4,]   10    9 157.04230\n[5,]    9    8  90.82891\n[6,]    8    6 140.01101\n```\n:::\n:::\n\n\nThe plot method for the MST include a way to show the observation numbers of the nodes in addition to the edge. As before, we plot this together with the township boundaries. We can see how the initial neighbour list is simplified to just one edge connecting each of the nodes, while passing through all the nodes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(shan_sp, border=gray(.5))\nplot.mst(shan.mst, \n         coordinates(shan_sp), \n         col=\"blue\", \n         cex.lab=0.7, \n         cex.circles=0.005, \n         add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n### 8.5. Computing Spatially Constrained Clusters Using SKATER Method\n\nThe code chunk below compute the spatially constrained cluster using [*skater()*](https://r-spatial.github.io/spdep/reference/skater.html) of **spdep** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclust6 <- skater(edges = shan.mst[,1:2], \n                 data = shan_ict, \n                 method = \"euclidean\", \n                 ncuts = 5)\n```\n:::\n\n\nThe *skater()* takes three mandatory arguments: - the first two columns of the MST matrix (i.e. not the cost), - the data matrix (to update the costs as units are being grouped), and - the number of cuts. Note: It is set to **one less than the number of clusters**. So, the value specified is [not]{.underline} the number of clusters, but the number of cuts in the graph, one less than the number of clusters.\n\nThe result of the *skater()* is an object of class **skater**. We can examine its contents by using *str()* of **utils** to display the internal structure of `clust6`, using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(clust6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 8\n $ groups      : num [1:55] 3 3 6 3 3 3 3 3 3 3 ...\n $ edges.groups:List of 6\n  ..$ :List of 3\n  .. ..$ node: num [1:22] 13 48 54 55 45 37 34 16 25 31 ...\n  .. ..$ edge: num [1:21, 1:3] 48 55 54 37 34 16 45 31 13 13 ...\n  .. ..$ ssw : num 3423\n  ..$ :List of 3\n  .. ..$ node: num [1:18] 47 27 53 38 42 15 41 51 43 32 ...\n  .. ..$ edge: num [1:17, 1:3] 53 15 42 38 41 51 15 27 15 43 ...\n  .. ..$ ssw : num 3759\n  ..$ :List of 3\n  .. ..$ node: num [1:11] 2 6 8 1 36 4 10 9 46 5 ...\n  .. ..$ edge: num [1:10, 1:3] 6 1 8 36 4 6 8 10 10 9 ...\n  .. ..$ ssw : num 1458\n  ..$ :List of 3\n  .. ..$ node: num [1:2] 44 20\n  .. ..$ edge: num [1, 1:3] 44 20 95\n  .. ..$ ssw : num 95\n  ..$ :List of 3\n  .. ..$ node: num 23\n  .. ..$ edge: num[0 , 1:3] \n  .. ..$ ssw : num 0\n  ..$ :List of 3\n  .. ..$ node: num 3\n  .. ..$ edge: num[0 , 1:3] \n  .. ..$ ssw : num 0\n $ not.prune   : NULL\n $ candidates  : int [1:6] 1 2 3 4 5 6\n $ ssto        : num 12613\n $ ssw         : num [1:6] 12613 10977 9962 9540 9123 ...\n $ crit        : num [1:2] 1 Inf\n $ vec.crit    : num [1:55] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"class\")= chr \"skater\"\n```\n:::\n:::\n\n\nThe most interesting component of this list structure is the groups vector containing the labels of the cluster to which each observation belongs (as before, the label itself is arbitary). This is followed by a detailed summary for each of the clusters in the edges.groups list. Sum of squares measures are given as ssto for the total and ssw to show the effect of each of the cuts on the overall criterion.\n\nWe can check the cluster assignment by using the `groups` argument of `clust6` in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccs6 <- clust6$groups\nccs6\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 3 3 6 3 3 3 3 3 3 3 2 1 1 1 2 1 1 1 2 4 1 2 5 1 1 1 2 1 2 2 1 2 2 1 1 3 1 2\n[39] 2 2 2 2 2 4 1 3 2 1 1 1 2 1 2 1 1\n```\n:::\n:::\n\n\nWe can find out how many observations are in each cluster by means of the table command. Parenthetically, we can also find this as the dimension of each vector in the lists contained in `edges.groups`. For example, the first list has node with dimension 12, which is also the number of observations in the first cluster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ccs6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nccs6\n 1  2  3  4  5  6 \n22 18 11  2  1  1 \n```\n:::\n:::\n\n\nFinally, we can also plot the pruned tree that shows the five clusters on top of the townshop area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(shan_sp, border=gray(.5))\nplot(clust6, \n     coordinates(shan_sp), \n     cex.lab=.7,\n     groups.colors=c(\"red\",\"green\",\"blue\", \"brown\", \"pink\"),\n     cex.circles=0.005, \n     add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\n### 8.6. Visualising Clusters in Choropleth Map\n\nThe code chunk below is used to plot the newly derived clusters by using SKATER method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups_mat <- as.matrix(clust6$groups)\nshan_sf_spatialcluster <- cbind(shan_sf_cluster, as.factor(groups_mat)) %>%\n  rename(`SP_CLUSTER`=`as.factor.groups_mat.`)\nqtm(shan_sf_spatialcluster, \"SP_CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nFor easy comparison, we place both the hierarchical clustering and spatially constrained hierarchical clustering maps next to each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhclust.map <- qtm(shan_sf_cluster,\n                  \"CLUSTER\") + \n  tm_borders(alpha = 0.5) \n\nshclust.map <- qtm(shan_sf_spatialcluster,\n                   \"SP_CLUSTER\") + \n  tm_borders(alpha = 0.5) \n\ntmap_arrange(hclust.map, shclust.map,\n             asp=NA, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex3_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\nThe difference between the SKATER approach versus hierarchical clustering is clear - the former takes into account the spatial configuration of the towns and cluster those closer in proximity (neighbours) as seen on the plot on the right, while the former shows clusters that are all over the place. This allows us to further study the ICT PRs in Shan State and advice on practical questions in relation to them.\n",
    "supporting": [
      "Hands-on_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\r\n<script src=\"../site_libs/plotly-binding-4.10.0/plotly.js\"></script>\r\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/plotly-main-2.5.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}